### ISSUE TITLE
issuse base on 0.1.4

### ISSUE THREAD

**Issue by bluetoothbiao** [shd101wyy/vscode-markdown-preview-enhanced#10]
* [issues](#issues)
  * [toc](#toc)
  * [improt pdf file](#improt-pdf-file)

# environment

1.  MPE test base on 0.1.4
2.  win10 64
3.  VS code version 1.13.1

## toc

1.  has no effect
2. if there is a active atom open the same file it may lead to the atom's markdown-preview-enhanced TOC not working.

## improt pdf file

1. the same as [can't open the file ](https://github.com/shd101wyy/markdown-preview-enhanced/issues/457
)

**Comment by shd101wyy** [comment]
If you used `Create TOC` command, then your TOC will only be updated when you save the file.

**Comment by bluetoothbiao** [comment]
type
```
<!-- toc -->

<!-- tocstop -->
```
 then save . 

The same.

**Comment by bluetoothbiao** [comment]
change to [toc]  or cmd create toc  is ok now.
