### ISSUE TITLE
Can't print the background using Puppeteer

### ISSUE THREAD

**Issue by cychen2021** [shd101wyy/vscode-markdown-preview-enhanced#102]
When using Puppeteer to print Markdown to PDF, the background can't be printed even the "markdown-preview-enhanced.printBackground" option is set to "true".
I checked the source code and found it's because when calling the related Puppeteer function, Mume doesn't use the option that allowed background to be printed.

**Comment by shd101wyy** [comment]
Hi, @nomanous ,

The solution so far is to add a front matter that defines the options of [page.pdf(options)](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#pagepdfoptions) function.  
For example:  

```markdown
---
chrome:
    printBackground: true
    margin: 0
---

# Your markdown content
```

Thank you.

**Comment by shd101wyy** [comment]
This issue should be fixed now. Thank you.
