### ISSUE TITLE
无法导入css

### ISSUE THREAD

**Issue by siriuscc** [shd101wyy/vscode-markdown-preview-enhanced#105]
```
@import "mystyle.css"
```
无效了，只能导入less

**Comment by shd101wyy** [comment]
点击预览右上方的刷新按钮刷新?

**Comment by siriusprofessor** [comment]
不行哦
![image](https://user-images.githubusercontent.com/16629888/38788866-09470d54-4169-11e8-8390-eafa3c82a9b1.png)

**Comment by shd101wyy** [comment]
把 `test.css` 发我看看？

**Comment by siriusprofessor** [comment]
test.css
```
#my-id{
	background: #272822;
}

#my-id h1{
	color: aqua;
}

#my-id p code{
	color:#e33;
	background: #f0fabc;
}#my-id{
	background: #272822;
}

#my-id h1{
	color: aqua;
}

#my-id p code{
	color:#e33;
	background: #f0fabc;
}
```

**Comment by shd101wyy** [comment]
不太清楚，估计是个 BUG，等我找到解决方法了再告诉你吧

**Comment by nomanous** [comment]
检查了一下代码，原因是要把"markdown-preview-enhanced.enableScriptExecution"选项打开，参见Issue#107

**Comment by addone** [comment]
碰到了相同问题，找了一整天天才发现了这个帖子。建议把相关信息加入官网文档（定制style的相关文档完全没提到这个选项）或是选项设置的说明（选项中有提到javascript但没提及CSS）。
