### ISSUE TITLE
Cannot open preview in latest version

### ISSUE THREAD

**Issue by KimikoMuffin** [shd101wyy/vscode-markdown-preview-enhanced#108]
Using the `ctrl+k, ctrl+v` shortcut in version 0.3.5 results in a `command 'markdown-preview-enhanced.openPreview' not found` message appearing.

Selecting "Markdown Preview Enhanced: Open Preview" from the command pallet *also* results in `command 'markdown-preview-enhanced.openPreview' not found`.

**Comment by shd101wyy** [comment]
Try deleting "~/. mume" and reinstalling this extension?

**Comment by shd101wyy** [comment]
btw it is ctrl+k then press v, not ctrl+k then ctrl+v.

**Comment by KimikoMuffin** [comment]
Oh, right. Well, either way, deleting ~/.mume fixed it, thanks!

**Comment by shd101wyy** [comment]
No problem

**Comment by shkey** [comment]
@shd101wyy I also encountered this problem, but there is no "~/. mume" folder in my directory. Then I tried to reinstall the expansion, but it still didn't solve the problem. So what should I do to solve it?

**Comment by zhyishen** [comment]
shkey's way works for me, only delete `~/.mume` is not enough, you have to delete `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.3.5` as well.

**Comment by pamalvarez** [comment]
How can I delete ~`/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.3.5` ? Thanks!

**Comment by shd101wyy** [comment]
Uninstalling the extension from vscode will delete `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.3.5`

**Comment by bert2** [comment]
I ran into this issue today. None of the ways described above worked for me.

**Comment by glodov** [comment]
I've removed `rm -r ~/. mume` it did not help.
So, I've removed `rm -r ~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.5.3/`.
Restarted VSCode.
Installed a plugin again and it works now.

**Comment by KantiCodes** [comment]
@bert2 Didn't you also remove mume ?

**Comment by bert2** [comment]
> @bert2 Didn't you also remove mume ?

Don't remember, but if so, I would have listed that in the steps above. So I guess I didn't delete `~/. mume`.

Anywat, I think it's safe to delete it when you want to re-install.

**Comment by beardred** [comment]
Hi Together,
i have the same issue now and already deleted `~/.mume` and `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.8.4` and tried all combinations of restarting when installing and uninstalling..

Any advice?

**Comment by beardred** [comment]
If you're stumbling in here through google: 
There's a more recent issue to this topic -> https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/1238
