### ISSUE TITLE
Unable to open '': Invalid file resource (file://c:\users\milen\.markdown-preview-enhanced\mermaid_config.js). Close Error

### ISSUE THREAD

**Issue by milenstack** [shd101wyy/vscode-markdown-preview-enhanced#11]
Unable to open '': Invalid file resource (file://c:\users\milen\.markdown-preview-enhanced\mermaid_config.js).
Close
Error

**Comment by shd101wyy** [comment]
这个是 windows 下的路径问题，你现在可以先手动到 `C:\users\milen\.markdown-preview-enhanced\mermaid_config.js`

**Comment by shd101wyy** [comment]
@milenstack Fixed. 
Thanks.
