### ISSUE TITLE
表格不支持扩展语法(table can't support Extended syntax )

### ISSUE THREAD

**Issue by siriuscc** [shd101wyy/vscode-markdown-preview-enhanced#115]
原生markdown不支持table 的扩展语法：

```
| a | b |
|---|---|
| >	| 1 |
| 2	|  | 
```
![image](https://user-images.githubusercontent.com/16629888/41515204-d5567306-72df-11e8-8617-93126c5f1c04.png)

在官方文档中描述是：
![image](https://user-images.githubusercontent.com/16629888/41515220-f46fe812-72df-11e8-894f-203ca8b7fc12.png)

然而我尝试了很多次都没成功

**Comment by shd101wyy** [comment]
得在设置中把 enableExtendedTableSyntax 这个选项开启

**Comment by siriuscc** [comment]
thank you!
