### ISSUE TITLE
使用prince导出pdf只有一页

### ISSUE THREAD

**Issue by TivJsou** [shd101wyy/vscode-markdown-preview-enhanced#121]
prince 使用的最新版本，官网下载的zip包。(没有windows 管理员权限，没有尝试msi版）
导出的pdf只有第一页。
只看这一页的话，样式字体是没有问题的。
但不管多大的markdown文件，导出为pdf后都只有一页。

MPE:0.3.5
vscode:1.25.1
prince:12

**Comment by shd101wyy** [comment]
这个是解决了吗？问题怎么关闭了。

**Comment by shd101wyy** [comment]
吼，看到了。

**Comment by TivJsou** [comment]
@shd101wyy  https://github.com/shd101wyy/markdown-preview-enhanced/issues/925
重新开了issue,原因是vue.css
