### ISSUE TITLE
CSS not working with exported HTML or when viewed in Browser

### ISSUE THREAD

**Issue by anishmittal2020** [shd101wyy/vscode-markdown-preview-enhanced#130]
I have set the following CSS in the settings and the CSS works when html is previewed in a tab. But when exported or Opened in the browser, the CSS doesn't work anymore but it takes some predefined CSS.

```json
"markdown-preview-enhanced.previewTheme":  "solarized-light.css",
```

**Comment by shd101wyy** [comment]
there is a setting called printBackground if i recall correctly. You need to enable it.

Or add print_background: true to front matter

**Comment by anishmittal2020** [comment]
Thank you! :)
