### ISSUE TITLE
Changing .mume/ path

### ISSUE THREAD

**Issue by ketozhang** [shd101wyy/vscode-markdown-preview-enhanced#134]
I've asked a similar question in #88 about syncing the directory `~/.mume` (Windows `%USERPROFILE%\.mume`) so that I can move around the mathjax config file.

[VSCode now support portability ](https://code.visualstudio.com/docs/editor/portable) thus I would like to request a minor change to MPE which is to add a user preferences to allow changing where .mume/ is located. If you cannot provide a syncing feature the VSCode portable mode should be sufficient.

```json
"markdown-preview-enhanced.mumePath": "~/.mume"
```

**Comment by shd101wyy** [comment]
Hi @ketozhang This is a very good suggestion. I will open the same issue in [mume](https://github.com/shd101wyy/mume) repository. Thanks.
