### ISSUE TITLE
ParseError: KaTeX parse error: Expected 'EOF', got '月' at position 6: 12.5/月̲，

### ISSUE THREAD

**Issue by everwanna** [shd101wyy/vscode-markdown-preview-enhanced#138]
Markdown source has some Chinese characters, such as
```
$12.5/月
```
MPE gets some error,
```
ParseError: KaTeX parse error: Expected 'EOF', got '月' at position 6: 12.5/月̲，
```

**Comment by shd101wyy** [comment]
That is because `$` is the math delimiter. For example: `$x+1$` will be rendered by KaTeX.  
You could go to the package settings, search for `Math Rendering Option`, then disable it.  
Or you could write your markdown as `\$12.5/月`. Put `\` ahead `$` to escape.  
Thanks

**Comment by everwanna** [comment]
Thanks!
