### ISSUE TITLE
Header and Footer with Puppeteer PDF?

### ISSUE THREAD

**Issue by mrbmi513** [shd101wyy/vscode-markdown-preview-enhanced#142]
I would like to be able to add a custom header/footer to PDFs made with Puppeteer, including the option for page numbers. If this is already possible, how would I go about doing that?

**Comment by shd101wyy** [comment]
Hi @mrbmi513 . Yes it is possible.
You will first install the newest version of puppeteer.
Then in your markdown file, write the following front-matter:

```
---
puppeteer:
  displayHeaderFooter: true
  headerTemplate: "<span>This is header</span>"
  footerTemplate: "<span>This is footer</span>"
---
```

Inside `puppeteer` section, you could specify the [pdf print options](https://github.com/GoogleChrome/puppeteer/blob/v1.8.0/docs/api.md#pagepdfoptions).
You may need to specify the css for your header and footer yourself.

Thanks
