### ISSUE TITLE
Rendering problem

### ISSUE THREAD

**Issue by maxim-ge** [shd101wyy/vscode-markdown-preview-enhanced#144]
I think that update from 24 Sept 2018 changed behavior.

First thing is about wrapping:

![Note](https://i.paste.pics/6ea4b6f71667da97b64ab80e0297216f.png?trs=e2de237d0b2ced87b8a756ecc930cea7ab4dbed7116b9f26e684050ccbcd0b13)

That is ok, I can live with it.  But graphs have worse situation:

![Note](https://i.paste.pics/7ef03cf3424aacbc12f8a43bb4a5affc.png?trs=e2de237d0b2ced87b8a756ecc930cea7ab4dbed7116b9f26e684050ccbcd0b13)

**Comment by shd101wyy** [comment]
yes go to package settings then change mermaid theme to "default".

**Comment by maxim-ge** [comment]
Yes that worked

**Comment by shd101wyy** [comment]
I just upgrade mermaid to version `8.0.0-rc.8`. I think that is the cause.

**Comment by maxim-ge** [comment]
Nice support speed. Made a small donation.
