### ISSUE TITLE
All objects are rendered as black boxes

### ISSUE THREAD

**Issue by louagej** [shd101wyy/vscode-markdown-preview-enhanced#149]
### In diagrams TD, LR or Gantt, the objects should appear with the default theme:
here how it should be: [Mermaid Live Editor](https://mermaidjs.github.io/mermaid-live-editor/#/view/eyJjb2RlIjoiZ3JhcGggVERcbkFbQ2hyaXN0bWFzXSAtLT58R2V0IG1vbmV5fCBCKEdvIHNob3BwaW5nKVxuQiAtLT4gQ3tMZXQgbWUgdGhpbmt9XG5DIC0tPnxPbmV8IERbTGFwdG9wXVxuQyAtLT58VHdvfCBFW2lQaG9uZV1cbkMgLS0-fFRocmVlfCBGW2ZhOmZhLWNhciBDYXJdXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9fQ)

```mermaid
graph TD
A[Christmas] -->|Get money| B(Go shopping)
B --> C{Let me think}
C -->|One| D[Laptop]
C -->|Two| E[iPhone]
C -->|Three| F[Car]
```
### In vscode-mermaid-preview TD, LR or Gantt, the object are displayed as black boxes
This is also in the rendered html file.
Screenshot:
![image](https://user-images.githubusercontent.com/7229592/46147627-4ed78500-c266-11e8-9fb3-f62e0ea904b4.png)

   * Preview mode: Markdown Preview Enhanced
   * Theme used: dark

**Comment by shd101wyy** [comment]
Please go to the package settings, then change the `mermaidTheme` to default. It will work again. Thanks.

https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/144

**Comment by louagej** [comment]
@shd101wyy ,
The setting was still on default.
But after changing it to forest then back to default, it solved the issue.
So, thank you for your tip!

**Comment by nonprofittechy** [comment]
Changing the theme worked for me too, but I think this is still a bug in the extension. It should work on first install...
