### ISSUE TITLE
Mermaid preview, graph will be dark

### ISSUE THREAD

**Issue by StinaSten** [shd101wyy/vscode-markdown-preview-enhanced#151]
Version 0.3.8

mermaid graph will have black background and some grey text. 

User setting is by default:
"markdown-preview-enhanced.mermaidTheme": "mermaid.css",

Used exactly the same in my own settings and got error message on the usage of mermaid.css.
Used setting:
"markdown-preview-enhanced.mermaidTheme": "default",
fixed the problem.

**Comment by telesoho** [comment]
![image](https://user-images.githubusercontent.com/10979091/46511419-7e4f4880-c889-11e8-8b88-4079ecbe960d.png)
Used setting:
"markdown-preview-enhanced.mermaidTheme": "forest"
fixed my problem.
![image](https://user-images.githubusercontent.com/10979091/46511581-6d530700-c88a-11e8-91ce-278851c48d82.png)

**Comment by mark-anders** [comment]
I ran into the same issue. All of my diagrams were black. For me, going into VSCode settings and simply selecting any of the themes fixed it. I then went back to default and that worked too.

**Comment by tongchao199** [comment]
@telesoho cool, fix mine problem.
markdown-preview-enhanced.mermaidTheme setting in $HOME/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.3.11/package.json

**Comment by adamal** [comment]
To clarify @mark-anders 's suggestion: It's the Markdown Preview Enhanced's theme for Mermaid, you need to switch. 
So: 
Extensions > click gear-icon > configure extension settings > change Markdown-preview-enhanced: Mermaid Theme back and forth > Renders correctly
