### ISSUE TITLE
Could parse the vscode variable?

### ISSUE THREAD

**Issue by swordow** [shd101wyy/vscode-markdown-preview-enhanced#157]
Paste Image is an extension for markdown in vscode to paste the image from the clipboard.
And it could set the image store path, but if the file is moved away, the index to the image is wrong.
If all the image stored in one place indexed from the project root, and the markdown preview enhanced could parse the vscode variable like this : 

\!\[\]\(${ProjectRoot}/images/xxxxx.png)

Even if the md file moved away, the markdown preview enhanced could parse the ProjectRoot to the right value.

**Comment by shd101wyy** [comment]
If your path starts with `/`, then it is the path relative to the project root. So you don't need `${ProjectRoot}` variable.

**Comment by swordow** [comment]
> If your path starts with `/`, then it is the path relative to the project root. So you don't need `${ProjectRoot}` variable.

Cool~nice job!
