### ISSUE TITLE
URL with question mark(?) opens file explorer

### ISSUE THREAD

**Issue by Andrew-w-w** [shd101wyy/vscode-markdown-preview-enhanced#158]
URL with question mark(?) opens file explorer instead of web page when clicked in preview

example:
```
[ne555 timer](https://www.mouser.co.uk/ProductDetail/Texas-Instruments/NE555P?qs=sGAEpiMZZMsG1k5vdNM%2fc6UNh9pCnCAm)
```

enviornment:
vscode on windows 10 with firefox as the default browser

Link works fine from:
- html output (right click open in browser).
- vscode built it preview
- control click of url in md source

**Comment by shd101wyy** [comment]
@Andrew-w-w should be fixed now. Thanks!

**Comment by Andrew-w-w** [comment]
All good, Thanks
