### ISSUE TITLE
Error:Cannot read property 'filter' of undefined.

### ISSUE THREAD

**Issue by wkindling** [shd101wyy/vscode-markdown-preview-enhanced#160]
After I install the vscode-markdown-preview-enhanced, it cannot render the preview page and throw out an error:Unable to open 'MPE Preview': Cannot read property 'filter' of undefined.

I have tried to uninstall it and download again but it still has this error. Even I reinstall my vs-code and it still doesn't work.

My operating system is Windows10, and my vs-code's edition is the latest.

**Comment by shd101wyy** [comment]
Can I see your JavaScript console? Click `Help` then click `Toggle Developer Tool`. Thanks

**Comment by shd101wyy** [comment]
btw did you save your file to local disk?

**Comment by shd101wyy** [comment]
would be great if you can send me a screenshot of the project panel, like below:

![default](https://user-images.githubusercontent.com/1908863/47612937-f2c57380-da52-11e8-9e32-0f13126cdd2f.PNG)

**Comment by wkindling** [comment]
Thanks a lot for your reply!
And here is the js console interface

I have saved my file to local but the problem still exists.
The project panel is as follows:



Best Wishes!
------------------ 原始邮件 ------------------
发件人: "Yiyi Wang"<notifications@github.com>;
发送时间: 2018年10月28日(星期天) 下午2:41
收件人: "shd101wyy/vscode-markdown-preview-enhanced"<vscode-markdown-preview-enhanced@noreply.github.com>;
抄送: "Hao"<422599446@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [shd101wyy/vscode-markdown-preview-enhanced] Error:Cannot readproperty 'filter' of undefined. (#160)




btw did you save your file to local disk?

**Comment by wkindling** [comment]
Here is the js console interface.
![1](https://user-images.githubusercontent.com/23055417/47613018-86358d80-dac1-11e8-9fee-ae0bd5cbcedc.png)
And the project panel is as follows:
![2](https://user-images.githubusercontent.com/23055417/47613022-ba10b300-dac1-11e8-91a3-e4f34cec2ed8.png)

**Comment by shd101wyy** [comment]
@wkindling Oh that is because you opened a file that is not in your workspace.
我猜是因为你打开的那个文件不在 `PAPER`  这个目录下所以出错了。你 `Add Folder To Workspace` 然后打开那个文件所在的文件夹应该就好了。
如果我猜错的话，可否方便把你的文件夹发到我的邮箱？

应该是个 BUG，我找时间休下。多谢。

**Comment by wkindling** [comment]
的确，把文件放到paper目录下就可以了。非常感谢：）
