### ISSUE TITLE
解决v0.3.9--Unable to open 'MPE Preview': Cannot read property 'uri' of undefined.

### ISSUE THREAD

**Issue by srcist** [shd101wyy/vscode-markdown-preview-enhanced#162]
如果直接创建一个`.md`文件, 用vscode打开进行预览就会报错, 但是如果将文件放到一个文件夹中, 比如文件夹命名为`test`, 再在vscode中打开这个文件对`.md`进行预览(右键该文件夹选择`open with code`), 预览就能成功.
然而我记得以前的版本是可以直接预览`.md`文件的~

**Comment by shd101wyy** [comment]
是个 bug，我今天修复下。

**Comment by shd101wyy** [comment]
@srcist 应该修好了，抱歉。
