### ISSUE TITLE
failed to render png of compiled md when defaut assets path

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/vscode-markdown-preview-enhanced#17]
Hi @shd101wyy !

see here.

https://github.com/tmori3y2/MPE-Test/tree/master/vscode/import

**Comment by shd101wyy** [comment]
Hi @tmori3y2 

Which markdown file?

**Comment by shd101wyy** [comment]
Okay I see, will be fixed.

**Comment by shd101wyy** [comment]
Oh I see, this is not a bug. 
`/assets` means the images will be exported to the `assets` directory relative to your **project directory**. If you want to save it to your current directory, you need to write it as `./assets` or `assets`.  
Thanks

**Comment by tmori3y2** [comment]
I'm sorry I did not have enough explanation.

test_import_001_.md is compiled md of test_import_001.md.

https://raw.githubusercontent.com/tmori3y2/MPE-Test/master/vscode/import/test_import_001_.md

MPE generated the relative windows style path "..\..\assets\ed7441fe68d9fd503e0cd6ee55402c5e0.png".

Please note that the path separator is not escaped.

MPE preview window failed to render png of test_import_001_.md because the resolved path of "..\..\assets\ed7441fe68d9fd503e0cd6ee55402c5e0.png" is "....\assets\ed7441fe68d9fd503e0cd6ee55402c5e0.png".

**Comment by tmori3y2** [comment]
Since the Windows style separator also has a problem with the Atom version of MPE, it may be better to replace '\\' with '/'.

**Comment by shd101wyy** [comment]
Understood!

**Comment by shd101wyy** [comment]
@tmori3y2 Should be fixed now! 

BTW, I just created a core library called [MUME](https://github.com/shd101wyy/mume), and my plan is to let both vscode and atom versions share the same core.  

Thanks :)

**Comment by tmori3y2** [comment]
Thanks a lot!
