### ISSUE TITLE
Every command+s save file causes the preview view to move up

### ISSUE THREAD

**Issue by WuErPing** [shd101wyy/vscode-markdown-preview-enhanced#1731]
Every command+s save file causes the preview view to move up

**Comment by WuErPing** [comment]
After testing, I confirmed that it was caused by mermaid

**Comment by shd101wyy** [comment]
Thanks. I will take a look.

**Comment by WuErPing** [comment]
Thanks.  More Info：


Published
2017-6-13, 08:43:02
Last released
2023-8-22, 21:41:42
Last updated
2023-8-23, 10:59:31
Identifier
shd101wyy.markdown-preview-enhanced

**Comment by WuErPing** [comment]
Fixed, thank you very much

More Info
Published
2017-6-13, 08:43:02
Last released
2023-9-17, 22:57:39
Last updated
2023-9-18, 09:29:02
Identifier
shd101wyy.markdown-preview-enhanced
