### ISSUE TITLE
PDF export using puppeteer fails. Error: Chrome path is not set.

### ISSUE THREAD

**Issue by daniel-larraz** [shd101wyy/vscode-markdown-preview-enhanced#1734]
Version 0.6.10 and below work fine. Only version 0.7.0 fails.

VS Code version: 1.81.1
OS: Ubuntu 20.04

**Comment by shd101wyy** [comment]
you can set the absolute path of your chrome to "markdown-preview-enhanced.chromePath"

**Comment by shd101wyy** [comment]
On Ubuntu, you can run command in your terminal "whereis google-chrome" to locate the executable. it's usually "/usr/bin/google-chrome". 

Then in the vscode you can set the setting "markdown-preview-enhanced.chromePath"

**Comment by daniel-larraz** [comment]
@shd101wyy , thanks for you comment.

When I set the path, I get the following error: `TypeError: Invalid host defined options`.

**Comment by shd101wyy** [comment]
@daniel-larraz may I see your chrome path setting?

**Comment by shd101wyy** [comment]
You are right. Here is a bug. I will fix it soon.

**Comment by shd101wyy** [comment]
@daniel-larraz the bug should be fixed now in 0.7.1.  

You can also leave `markdown-preview-enhanced.chromePath` empty now, so the MPE will look for the chrome executable automatically.  

Thank you!
