### ISSUE TITLE
Code chunk output with tag, preview problem

### ISSUE THREAD

**Issue by zegal1974** [shd101wyy/vscode-markdown-preview-enhanced#1736]
Code chunk, When output is text, those with<tag>will be displayed in HTML format.

```python{cmd=true}
print("<a href=`'#link'>link</a>")
```

The preview display is just a LINK.

Can add ``<code>`` to the output ``<pre>``?

**Comment by shd101wyy** [comment]
Oh I see. We probably want to escape the output text so it won’t rendered as html in <pre>. I will submit a patch to fix it this week 👍

**Comment by shd101wyy** [comment]
Should be fixed in `0.7.2`. Thank you.
