### ISSUE TITLE
Error rendering plantuml graph after the update to version 0.7.1

### ISSUE THREAD

**Issue by AzzoliniDavide** [shd101wyy/vscode-markdown-preview-enhanced#1738]
After the update to version 0.7.1
The render of a markdown file containing

```
```plantuml
@startuml
...
```

Give this error, on both linux and windows VSCode plugin

```
Error: plantuml.jar file not found: ""

Please download plantuml.jar from https://plantuml.com/download.  


If you are using VSCode, then please set the setting "markdown-preview-enhanced.plantumlJarPath" to the absolute path of plantuml.jar file. 
```

**Comment by shd101wyy** [comment]
Right we do now include `plantuml.jar` in this package anymore.  

You can download `plantuml.jar`  then set `markdown-preview-enhanced.plantumlJarPath` to the jar file.  

Another option is to set `markdown-preview-enhanced.plantumlServer` to `https://kroki.io/plantuml/svg/` so it will use Kroko to render plantuml.

**Comment by aqz-saito** [comment]
I'm also encountering same problem. It was no problem before. This error doesn't occur when restored v0.6.10. But this error occurs when updated to v0.7.1 or later. I've not tried to test v0.7.0.

**Comment by shd101wyy** [comment]
hey guys. like I said above we dont not include plantuml.jar file in our MPE extension. So you can either download the plantuml.jar file yourself then set “markdown-preview-enhanced.plantunlJarPath” to it, or you can simply set “markdown-preview-enhanced.plantumlServer” to “https://kroki.io/plantuml/svg/” if you don't want to download the jar file.

**Comment by springjazzy** [comment]
I've tried setting `markdown-preview-enhanced.plantumlServer` or `markdown-preview-enhanced.plantumlJarPath`.
What I see in preview window in either of these cases is this:

![2023-09-07_10-21-09](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/16219710/dde2d15b-7a0a-4cb8-836b-daeb21e96a6b)

or

![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/16219710/8d1f540e-75c9-4bf2-9ce3-9bc7714e0255)

I'm currently on latest `v0.7.3` version.

**Comment by shd101wyy** [comment]
@springjazzy Can you also try:

```
"markdown-preview-enhanced.plantumlServer": "https://www.plantuml.com/plantuml/svg/"
```

I tried `https://kroki.io/plantuml/svg/` and it works for me though.

**Comment by springjazzy** [comment]
Interestingly that I decided to check whether playuml is actually working on my machine according to `https://plantuml.com/en/faq-install`. Everything worked fine. Then I returned to VSCode and now I see my diagrams. Don't know what `magic` happened but now everything works. Thanks for response!

**Comment by shd101wyy** [comment]
Thank you @springjazzy . Please let us know if you have any more questions :)

We decided to remove the plantuml.jar because we are also supporting the MPE extension in the web https://vscode.dev now. Including the jar file will make the extension beyond the size limit.

**Comment by shd101wyy** [comment]
Guys I am closing this issue. Please leave comment here if you still have questions. Thank you.

**Comment by Ale-NeuroTech** [comment]
I had the same problem, but I realized that I had not installed Java. That solved the problem

**Comment by nethawkChen** [comment]
Using "https://kroki.io/plantuml/svg/" for rendering works very well, but it seems unstable and often fails to connect. Are there any alternative solutions?
