### ISSUE TITLE
更新到0.7.2版本之后，单一预览页的功能会失效

### ISSUE THREAD

**Issue by Sun2030** [shd101wyy/vscode-markdown-preview-enhanced#1740]
在0.7.1版本及之前，可以通过勾选以下两个选项，实现单一预览页自动切换至焦点（正在编辑的）markdown文档的预览

Markdown-preview-enhanced: Automatically Show Preview Of Markdown Being Edited
Markdown-preview-enhanced: Single Preview

但在今天更新更新至0.7.2版本之后，单一预览页的功能失效了，现在焦点切换到其他markdown文档时会打开新的预览页，也就是说会同时存在多个预览页，使用时很不习惯，希望能修复这个问题

**Comment by shd101wyy** [comment]
可能是今天放的更新的问题 :joy: 我应该明天才能再仔细看看了。  
你是直接从一个 Workspace 打开的 md 文件，还是没有 Workspace 直接打开的 md 文件？

**Comment by shd101wyy** [comment]
[Screencast from 2023-09-05 23-02-56.webm](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/1908863/abd3251d-598b-4f22-8221-a5adf85b1e66)

这个是我在 qemu 里面跑的 windows 上的 vscode。

**Comment by Sun2030** [comment]
> 可能是今天放的更新的问题 😂 我应该明天才能再仔细看看了。 你是直接从一个 Workspace 打开的 md 文件，还是没有 Workspace 直接打开的 md 文件？
> 
> 最好可以发个截图或者 gif。谢谢

的确这个问题只有在打开不属于当前工作区的文档时才会出现
不过之前能够全局共享一个预览页，还是希望能够改回之前的机制，谢谢
以下是一个对这个问题的演示视频

https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/94839268/eebb0ca1-c6ff-431f-8f65-2bec293f3c2d

**Comment by shd101wyy** [comment]
应该是修复了。
