### ISSUE TITLE
Images are not embedded as base64 in HTML export [BUG] 

### ISSUE THREAD

**Issue by markusmorawitz77** [shd101wyy/vscode-markdown-preview-enhanced#1748]
**Describe the bug**
Embedding local images in html as base64 has worked for me some time ago without problems. Now with the latest version images are not exported as base64 but in some binary format. 

**Environment**
- OS: Windows 10
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.7.3

**To Reproduce**
I created a simple markdow (EmedImages.md) to display png file and export it to an html file using embed_local_images set to true.

**Expected behavior**
In the generated html  the image should be included as base64. 

**What I get**
But instead I get an html which seems to include the image not in base64 but as binary?

EmbedImages.md:
```
---
html:
  embed_local_images: true
  embed_svg: true
  offline: true
  toc: true
---

![](image.png)
```

![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/6226420/0ad8a6c5-5731-4b83-bcf8-bba7c2e14336)

**Comment by markusmorawitz77** [comment]
I have just reset the version of MPE to version 0.6.8 and with this version the behaviour is correct and the images are embedded as base64 strings es expected.

**Comment by shd101wyy** [comment]
Thank you. Will fix it.
