### ISSUE TITLE
[BUG] KaTeX config is broken in version 0.7.3

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [shd101wyy/vscode-markdown-preview-enhanced#1750]
**Describe the bug**

- The "Markdown preview enhanced: Open KaTeX Config" command is missing from the VS Code command palette (cmd + shift + p), and existing settings from previous versions (at `/Users/Username/.local/state/mume/katex_config.js`) is not recognized by the extension. I need to revert to v.0.7.0 to make custom KaTeX macros work again. 

- It seems that the extension settings are to be moved to `/Users/Username/.local/state/crossnote` in future versions. I tried to copy `katex_config.js` to this folder but it still does not work. 

**Environment**
- OS: macOS 13.5.1
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.7.3

**Comment by shd101wyy** [comment]
你得运行 `Markdown Preview Enhanced: Open Config Script`  打开 config 脚本然后重新输入 `katexConfig`:

```javascript
({
  katexConfig: {
  "macros": {}
},
  
  mathjaxConfig: {
  "tex": {},
  "options": {},
  "loader": {}
},
  
  mermaidConfig: {
  "startOnLoad": false
},
})
```

**Comment by shd101wyy** [comment]
文档没更新。我找个时间更新下文档。
