### ISSUE TITLE
[BUG] Slide embedded mermaid graph open in browser display not work

### ISSUE THREAD

**Issue by 9468305** [shd101wyy/vscode-markdown-preview-enhanced#1752]
**Describe the bug**
A slide markdown file contain embedded mermaid graph, display correct in preview. But display not work when open it in chrome browser.

HTML offline mode is same error.
HTML CDN hosted is correct.

**Environment**
- OS: macOS 12.0.1
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.7.3

**To Reproduce**

1. Create sample file

```txt
    ---
    presentation:
        theme: white.css
    ---
    
    <!-- slide -->
    
    # slide
    
    ```mermaid
    graph LR
    A -->B
    ```
```

2. Click on 'Open In Browser', launch Chrome and show.
3. <img width="350" alt="open in browser" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/4039620/2a78f81c-8076-46cc-ab3a-5e5c01575766">

4. Chrome DevTool Log
```bash
source-sans-pro.css:1     Failed to load resource: net::ERR_FILE_NOT_FOUND
DevTools failed to load source map: Could not load content for file:///Users/chenqi/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.7.3/crossnote/dependencies/reveal/js/reveal.js.map: 系统错误: net::ERR_FILE_NOT_FOUND
```

**Expected behavior**
It should as same as Preview.
<img width="235" alt="preview" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/4039620/9b7d3089-4cb0-4a2f-ac70-a529961cb6dd">

HTML Offline mode is same error. The output html file is 
[offline.txt](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/12583994/offline.txt)

**Comment by shd101wyy** [comment]
谢谢。我这周在准备一个比较大的更新。之后会修理一下这个 bug

**Comment by shd101wyy** [comment]
Should be fixed now. Please help check. Thanks.

**Comment by 9468305** [comment]
Perfect!

**Comment by Boom20230908** [comment]
我想组建 ios 逆向开发的团队, 想咨询一下您, 是否能加一下我的QQ或者微信 详情聊一下.? 
495203424  V:My_king_of_world
