### ISSUE TITLE
[BUG] Can't preview flowchart

### ISSUE THREAD

**Issue by ABackerNINI** [shd101wyy/vscode-markdown-preview-enhanced#1755]
**Describe the bug**
The recent version 0.7.x can't preview flow chart while the older versions could, e.g., v0.6.10.

**Environment**
- OS: Windows 10
- VSCode: 1.82.1
- Markdown Preview Enhanced: 0.7.3 

**To Reproduce**

A very simple flow chart as an example:

\```flow
start=>start: Start
end=>end: End
start->end
\```

**Expected behavior**
Screenshot of v0.6.10:
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/12003373/aa1d577f-e64e-4b79-ac9c-7aa14d10a83e)

**Screenshots**
Screenshot of v0.7.3:
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/12003373/006021a3-628f-4c36-b750-7bbf641f4c80)

**Additional context**

**Comment by shd101wyy** [comment]
Sorry flowchat is removed. Please use `mermaid` for flowchart: https://mermaid.js.org/syntax/flowchart.html
