### ISSUE TITLE
MathJax does not work in preview

### ISSUE THREAD

**Issue by tcbbd** [shd101wyy/vscode-markdown-preview-enhanced#1763]
By using developer tools of VSCode, we can see MathJax throws an error reporting that `t.getElementsByTagName` is not found. This is because MathJax expects an HTMLElement, while crossnote gives it a ReactJS wrapper, from which the real HTMLElement can only be accessed through `t.current`.

The `getElementsByTagName` is only used in MathML input code path, so if we change the default MathJax script URL to `somecdn/.../tex-chtml.js`, the annoying "something is wrong" error will not show up. But in that case, nothing will be rendered, as if no MathJax script is imported.

Note that this is only a bug in preview window, if you open the preview in browser, all the equations will be rendered correctly.

**Comment by shd101wyy** [comment]
Thank you. So this line is wrong: https://github.com/shd101wyy/crossnote/blob/master/src/webview/containers/preview.ts#L348

Could you please help submit a PR for that? I will publish a new version of the extension today.

**Comment by tcbbd** [comment]
So I created the PR, hope you can include the fix in the new version.

**Comment by deangl** [comment]
Still does not work after upgrade to the latest (2023-9-15 20:32:24) version.
