### ISSUE TITLE
[BUG]: Background Color Error

### ISSUE THREAD

**Issue by GrainRainy** [shd101wyy/vscode-markdown-preview-enhanced#1764]
When the length of the MD file is quite short, the background color I set is only displayed in positions with words. 

![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/77619434/83b037ae-4108-456c-a4e7-a3508c1302bc)

**Comment by shd101wyy** [comment]
Should be fixed now in 0.7.7. Thanks
