### ISSUE TITLE
[BUG] 'Back to top' feature not working in preview pane of v0.7.8

### ISSUE THREAD

**Issue by djherron** [shd101wyy/vscode-markdown-preview-enhanced#1769]
**Describe the bug**
The 'Back to top' icon in the top-right of the preview pane doesn't work. It doesn't do anything.

One can click the 'Toggle table of contents' icon to display the table of contents and then click a section link in the table of contents. This takes one to the top of the document. But if one then clicks the 'Toggle table of contents' again to close the table of contents, one is taken back to the original spot.

So there are actually two behavioural issues here, both of which prevent a user from getting back to the top of document.

**Environment**
- OS: MacOS Big Sur (11.7.9)
- VSCode: 1.82.2
- Markdown Preview Enhanced: 0.7.8 

**To Reproduce**
1. Open a .md document that has a Table of Contents generated by [TOC]
2. Activate Markdown Preview Enhanced
3. Click an item (section link) in the Table of Contents to jump deep into the document
4. Go to the top-right of the preview pane and click the ^ ('Back to top') icon. Nothing happens!

**Expected behavior**
Both the preview pane and the source editor pane should jump to the top of the document.

**Comment by shd101wyy** [comment]
Thanks. It's a bug. We will fix it soon.

**Comment by shd101wyy** [comment]
Should be fixed now in 0.7.9. Please help check when you have time. Thank you!

**Comment by djherron** [comment]
works great now for me; thanks very much!
