### ISSUE TITLE
[BUG] Inconsistent preview rendering in VS Code and external browsers

### ISSUE THREAD

**Issue by Yue-Zhengyuan** [shd101wyy/vscode-markdown-preview-enhanced#1771]
**Describe the bug**
The preview theme `none.css` is rendered differently in VS Code and external browsers. But in version 0.7.3, they look the same. 

**Environment**
- OS: macOS 13.5.1
- VSCode: 1.82.2
- Markdown Preview Enhanced: 0.7.8

**Screenshots**
- "Open in browser" with Microsoft Edge
<img width="251" alt="bug_Edge" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/43436192/fcdf5404-3609-4ec6-ac99-f981eadd5ab7">

- Version 0.7.3
<img width="232" alt="bug_073" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/43436192/dfe1edc7-01ef-438e-9993-92b74b757045">

- Version 0.7.8 (the line spacing is different from the Edge preview of generated HTML)
<img width="232" alt="bug_078" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/43436192/8bfd2c0b-0e5e-401c-a0e7-fe495071fc5f">

**Comment by shd101wyy** [comment]
It's because `Open In Browser` will use the `github-light.css` theme by default. If you still want it to use `none.css`, you need to set the following front-matter in your markdown document:

```
---
print_background: true
---
```

or you can set the setting:  `"markdown-preview-enhanced.printBackground": true,`

**Comment by shd101wyy** [comment]
This problem should be fixed in this commit: https://github.com/shd101wyy/crossnote/commit/3e4560b0887efbd20c712290219cdfdfd7161260

But I am still working on the branch of that commit. So I will push a fix this weekend.
