### ISSUE TITLE
Use CHROME_EXECUTABLE variables

### ISSUE THREAD

**Issue by FurryRbl** [shd101wyy/vscode-markdown-preview-enhanced#1772]
When I use Chrome (Puppeteer) I get the following error:
``` text
Error: Failed to launch the browser process! spawn C:Program Files (x86)GoogleChromeApplicationchrome.exe ENOENT TROUBLESHOOTING: https://pptr.dev/troubleshooting
```
I think this issue can be solved by using the 'CHROME_EXECUTABLE' environment variable to get the location of the chrome.exe file.

**Comment by shd101wyy** [comment]
You can set your chrome path in `markdown-preview-enhanced.chromePath` option.

`CHROME_EXECUTABLE` env variable is not always available.
