### ISSUE TITLE
[Feature Request] How to use github-markdown-css in MPE?

### ISSUE THREAD

**Issue by rockyzhz** [shd101wyy/vscode-markdown-preview-enhanced#1774]
How can we use the markdown style [css file][2] of [GitHub-Markdown-CSS][1] in MPE？
I've tried many times, but it doesn't seem to work.

[1]:https://github.com/sindresorhus/github-markdown-css
[2]:https://raw.githubusercontent.com/sindresorhus/github-markdown-css/main/github-markdown.css

**Comment by shd101wyy** [comment]
The MPE extension itself already provides the github-light.css and github-dark.css themes.

**Comment by shd101wyy** [comment]
You can customzie the css yourself. Github-markdown-css is not compatible with MPE.
