### ISSUE TITLE
[BUG] none.css background color not following setting properly

### ISSUE THREAD

**Issue by battaglia01** [shd101wyy/vscode-markdown-preview-enhanced#1777]
**Describe the bug**
After updating to v0.7.9, none.css seems to have some issues with the background color.

# Background Color and System Theme

The background color follows the system theme regardless of what the "Preview Color Scheme" setting is set to, even if the editor is in Light Mode and we do editorColorScheme. Worse, the text remains black. Here is what it looks like side-by-side:

<img width="1018" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/1020594/5a08a2af-2b08-458f-8774-0b37604639cc">

**Environment**
- OS: macOS 12.5
- VSCode: 1.82.2
- Markdown Preview Enhanced: v0.7.9

**Comment by shd101wyy** [comment]
This should be fixed now in version 0.7.10. Please help check when you are available. Thank you!
