### ISSUE TITLE
[BUG] none.css doesn't render correctly at all 

### ISSUE THREAD

**Issue by battaglia01** [shd101wyy/vscode-markdown-preview-enhanced#1778]
**Describe the bug**
After updating to v0.7.9, none.css seems to be totally broken rendering in VS Code on both macOS and Windows 10. Here is what it looks like rendering [this test Markdown file](https://raw.githubusercontent.com/mxstbr/markdown-test-file/master/TEST.md)

<img width="1436" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/1020594/8a9b6a2b-8762-4628-b657-3fa0ba190075">

You can see several problems:
1. `#Headers` aren't rendering
2. Nested lists don't indent for some reason
3. Paragraph breaks don't render - they just look like single line breaks
4. Blockquotes don't indent
5. In general, any kind of indentation doesn't render
6. Links render the same color as regular text

In general it's all messed up. **However**, when rendering in the browser using "print background" and none.css, this all renders correctly:

<img width="962" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/1020594/5fffbcf4-0040-4013-966b-c3b90901176e">

I've tried on both macOS 12.5 and Windows 10.

**Environment**
- OS: macOS 12.5 / Windows 10
- VSCode: 1.82.2
- Markdown Preview Enhanced: v0.7.9

**Comment by shd101wyy** [comment]
Will fix this bug this weekend :+1:

**Comment by shd101wyy** [comment]
This should be fixed now in version 0.7.10. Please help check when you are available. Thank you!
