### ISSUE TITLE
[Feature Request] Export to html using the Preview Theme css

### ISSUE THREAD

**Issue by ygtai** [shd101wyy/vscode-markdown-preview-enhanced#1786]
**Is your feature request related to a problem? Please describe.**
The html exported from preview has a style different than the Preview Theme.

**Describe the solution you'd like**
Export to html using the Preview Theme css.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by shd101wyy** [comment]
Hi @ygtai You can set `markdown-preview-enhanced.printBackground: true` in settings. Or add the following front-matter to your markdown document:

```markdown
---
print_background: true
---
```
