### ISSUE TITLE
[BUG] local style.less no longer working

### ISSUE THREAD

**Issue by lancezhange** [shd101wyy/vscode-markdown-preview-enhanced#1787]
**Describe the bug**
local style.less no longer working, but when i import the ~/.mume/style.less, it works(which indicates that the style.less file has no problem)

**Environment**
- OS: Mac 
- VSCode: 1.82.2
- Markdown Preview Enhanced: v0.7.10

**Screenshots**

when i import ~/.mume/style.less in the markdown file, it works as expected:
<img width="1492" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/4554635/96620c2b-e0dd-46e6-b41b-fba0332bc78f">

but without importing  ~/.mume/style.less, it tends  to render using the configed theme in vscode settting: "markdown-preview-enhanced.previewTheme": "solarized-light.css"
<img width="1586" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/4554635/bdd7433a-3f7a-413e-bcd4-707e72abaf9f">

**Additional context**

**Comment by lancezhange** [comment]
besides, when i downgrade to mpe verision v0.7.0, it works again

**Comment by DesZhang** [comment]
had the same problem on my mac after upgrade, and my config file for last version(style customization actually worked) got wiped out completely.

**Comment by shd101wyy** [comment]
Hey it's because the directory where we put config files are changed. You can run `Markdown Preview Enhanced: Customize Css` to re-initialize the config files.  

The old config files are located at:
- Windows: `%USERPROFILE%\.mume`
- *nix: `$XDG_CONFIG_HOME/.mume` or `$HOME/.local/state/mume`.

**Comment by battaglia01** [comment]
@shd101wyy this still doesn't seem to work on Mac. Where do the files need to be now? Because they're in `$HOME/.local/state/crossnote` and still getting this problem.

**Comment by shd101wyy** [comment]
You can run `Markdown Preview Enhanced: Customize Css (Global)` or `Markdown Preview Enhanced: Customize Css (Workspace)` to re-initialize the `style.less`.

**Comment by battaglia01** [comment]
@shd101wyy it looks like the workspace settings still work but global doesn't.
