### ISSUE TITLE
[BUG] 多级无序列表嵌套时都显示相同圆点

### ISSUE THREAD

**Issue by SolemnJudgment** [shd101wyy/vscode-markdown-preview-enhanced#1789]
# **Describe the bug**
多级无序列表嵌套时都显示相同圆点

# **Environment**
- OS: Windows 11
- VSCode: 1.81.0
- Markdown Preview Enhanced: 0.7.10

# **Expected behavior**
打开预览，多级无序列表嵌套时都显示相同圆点，记得之前版本多级无序列表嵌套时显示空心圆点和方块

# **Screenshots**
## Markdown Preview Enhanced预览效果：
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/85673749/0ba50b1f-6822-4f41-83fe-2b3757366fdb)

## VSCode原生预览效果：
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/85673749/06ea9e82-9f37-41ce-a674-a338364e145a)

**Comment by shd101wyy** [comment]
应该是修复了，谢谢！
