### ISSUE TITLE
[BUG] 左侧编辑后右侧边栏目录点击时无法正常跳转

### ISSUE THREAD

**Issue by SolemnJudgment** [shd101wyy/vscode-markdown-preview-enhanced#1790]
# **Describe the bug**
左侧编辑后右侧边栏目录点击时无法正常跳转

# **Environment**
- OS: Windows 11
- VSCode: 1.81.0
- Markdown Preview Enhanced: 0.7.10

# **To Reproduce**
1. 打开Markdown Preview Enhanced预览
2. 点击预览右侧按钮打开目录大纲
3. 此时点击右侧目录可以正常跳转
4. 返回左侧编辑器继续编辑并保存
5. 再次点击右侧目录预览会自动跳到[TOC]目录，无法正常跳转

# **Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/85673749/125ff4d8-3e23-4950-bb76-21ffa3900e2c)
![](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/85673749/2776fbfe-561e-41fd-bb57-b9eaa717a360.gif)

**Comment by shd101wyy** [comment]
应该是修复了，谢谢！
