### ISSUE TITLE
[BUG] Links broken and no longer add .md extension

### ISSUE THREAD

**Issue by battaglia01** [shd101wyy/vscode-markdown-preview-enhanced#1794]
**Describe the bug**
We can use Github's link Syntax to make a link to FileName.md as follows:

```Click here for [[FileName]] ```

Note there is no "md" at the end. We can also put different link text as follows (here is the bug):

```Click here for [[link text|FileName]]```

Again note there is no ".md" at the end of FileName.

This used to work, but as of 0.80 it seems to be broken: we get a file not found error. We instead need to put .md

```Click here for [[link text|FileName.md]]```

This has broken all of my links and it would be nice to be able to do it the old way again.

**Environment**
- OS: macOS 12.5
- VSCode: 1.82.2
- Markdown Preview Enhanced: 0.8.0

**Comment by shd101wyy** [comment]
I will remove the `processWikiLink` function support. It seems to increased the complexity.

**Comment by battaglia01** [comment]
OK, is there some other way?

**Comment by shd101wyy** [comment]
This should be working now in `0.8.1`. Please give it a try. Thanks
