### ISSUE TITLE
引用语法预览错误

### ISSUE THREAD

**Issue by Guo-Chenxu** [shd101wyy/vscode-markdown-preview-enhanced#1798]
**描述**

引用语法预览错误

**环境**

- OS: Windows 10
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.0

**详细描述**

markdown的引用语法 `>` 只能顶格写, 否则会预览错误 (虽然预览错误, 但是在导出的 `pdf` 文件中显示正常)

`MPE` 的显示:
<img src="https://cdn.jsdelivr.net/gh/Guo-Chenxu/imgs@main/imgs/202310061519424.png"/>

我希望的得到的显示 (也就是导出的 `pdf` 中的显示):
<img src="https://cdn.jsdelivr.net/gh/Guo-Chenxu/imgs@main/imgs/202310061523098.png"/>

**Comment by Guo-Chenxu** [comment]
刚试了一下, 把`MPE`降级到上一个版本`0.7.10`后, 这个问题就消失了, 所以应该只是这次更新出了一些问题

**Comment by SolemnJudgment** [comment]
我也有相同问题

**Comment by shd101wyy** [comment]
0.8.1 应该修复了。可以再试一试。谢谢

**Comment by Guo-Chenxu** [comment]
ok, 目前能够正常使用, 感谢作者修复bug
