### ISSUE TITLE
[BUG] 无序列表嵌套有序列表时，后续的空白行预览显示异常

### ISSUE THREAD

**Issue by SolemnJudgment** [shd101wyy/vscode-markdown-preview-enhanced#1799]
# **Describe the bug**
无序列表嵌套有序列表时，后续的空白行预览显示异常

# **Environment**
- OS: Windows 11
- VSCode: 1.81.0
- Markdown Preview Enhanced: 0.8.0

# **Expected behavior**
无序列表嵌套有序列表时，后续的空白行预览显示异常

# **Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/85673749/2134f5ec-221c-4de4-a80f-d02675f9d466)

**Comment by SolemnJudgment** [comment]
好像是后面的空白行显示异常

**Comment by shd101wyy** [comment]
0.8.1 应该修复了。可以再试一试。谢谢
