### ISSUE TITLE
[BUG] Markdown Preview code block not properly shown

### ISSUE THREAD

**Issue by szw0407** [shd101wyy/vscode-markdown-preview-enhanced#1800]
**Describe the bug**
Using a light theme such as `one-light.css` and a dark code block theme such as `github-dark.css`, the dark background of the code block is similar with the font shown in it.
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/107471539/029bb703-b154-40a8-ab11-faf8e141c012)
Hardly can I see it clearly.

Moreover, the 1st line in the code block seems to have a space in the front, when using `gothic-light` theme and `github-dark` code block theme, it is quite apparent:
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/107471539/3e623c96-4da6-4072-acf6-08123eedd41b)

Finally, when the code block is not closed, an unexpected line shows below:
Just input \`\`\`
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/107471539/6b4c41b3-2513-49c1-9499-c6721b6ef99a)

Anyway, this extension is quite nice, and I love it.

**Environment**
- OS: Windows 11
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**
just as I said before.

**Additional context**
Maybe you could consider in code blocks, all CSS can be reset.

**Comment by shd101wyy** [comment]
Should be fixed in `0.8.1`. Please help try again. Thank you.
