### ISSUE TITLE
[BUG] 代码块预览错误

### ISSUE THREAD

**Issue by EVANGELION-Air** [shd101wyy/vscode-markdown-preview-enhanced#1801]
**Describe the bug**
代码块预览错误

**Environment**
- OS: Windows 11
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.0

**Screenshots**
![QQ截图20231006170820](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/58524775/58533d01-a087-49e9-95e9-4330c0a0f566)

代码块渲染错误，其余平台正常显示，例如github在线预览：

![QQ截图20231006171211](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/58524775/0e598a08-b85b-4e4e-833a-3d8065ddd8a4)

**Comment by shd101wyy** [comment]
`0.8.1` 应该修复了。可以再试一试。谢谢

**Comment by shd101wyy** [comment]
可以发下整个文档不

**Comment by shd101wyy** [comment]
恩应该是 \`\`\`...\`\`\` 这个 inline code 造成的，推荐使用 \`...\` 就可以：

````markdown
# Temp

例如 `tar -rf all.tar *.gif` 就是将所有.gif 的文件增加到 all.tar 的包里去。

`tar`调用`gzip`：`gzip`是 GNU 组织开发的一个压缩程序， `.gz`结尾的文件就是`gzip`压缩的结果。与`gzip`相对的解压程序是`gunzip`，`-z`就是`tar`使用`gzip`压缩命令进行压缩，`tar -czf all.tar.gz *.jpg`, 就是将所有.jpg 文件打成一个`tar`包，并将其用`gzip`压缩，生成一个`gzip`压缩过的包，包名为 all.tar.gz。与之对应的，解包的命令是`tar -xzf all.tar.gz`。

`tar`调用`bzip2`：`bzip2`是一个压缩能力更强的压缩程序， `.bz2`结尾的文件就是`bzip2`压缩的结果。与`bzip2`相对的解压程序是`bunzip2`。使用`tar`调用`bzip2`的参数是`-j`。`tar -cjf all.tar.bz2 *.jpg`这条命令是将所有.jpg 的文件打成一个`tar`包，并且调用`bzip2`压缩，生成一个`bzip2`压缩过的包，包名为 all.tar.bz2。与之对应的解包命令是`tar -xjf all.tar.bz2`。

对于 .tar 文件：

```bash
tar -zxvf a.tar         # 解包到当前目录
tar -zxvf a.tar -C /xxx # 解包到指定位置
```
````

**Comment by shd101wyy** [comment]
不过我的 markdown transformer 确实也有问题。我到时候修一下，让 \`\`\`...\`\`\` 的 inline code 也没问题。

**Comment by shd101wyy** [comment]
\`\`\`...\`\`\` 的问题应该是修复了。
