### ISSUE TITLE
[BUG] 自定义样式 style.less 无法生效

### ISSUE THREAD

**Issue by ioshift** [shd101wyy/vscode-markdown-preview-enhanced#1803]
**Describe the bug**
自定义样式 style.less 无法生效

**Environment**
- OS: Windows 11
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**
1. `Ctrl+Shift+P`
2. 输入 `Markdown Preview Enhanced: Customize CSS (Global)`
3. 修改样式，如添加 `background-color: blue;`
4. 保存并重启 vscode
5. Preview无变化

**Comment by shd101wyy** [comment]
`0.8.1` 应该修复了。抱歉！
