### ISSUE TITLE
[BUG] `<dl>`定义列表的语法不可用；自定义parser也无法生效

### ISSUE THREAD

**Issue by van-lee-fxp** [shd101wyy/vscode-markdown-preview-enhanced#1804]
在上一个版本中，通过extend parser功能对markdown源文件的解析方式还能够体现在预览中，但是升级到新版本之后则无法生效，我自定义的解析功能都看不到效果。

在上一个版本中，`<dl>`定义列表可以通过以下的语法书写

```markdown
新名词1
:    对新名词1的解释说明

新名词2
~ 对新名词2的解释说明
```

但是升级到最新版本之后`<dl>`样式就失效了

下面两张图分别是同一份文档在新版和旧版中的预览效果。我对一些常用的但Markdown原生语法未支持的格式进行了自定义parser.

![Code_Mk7ijQKPKc](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/c39c4904-c20f-4d24-a64e-2247435170d2)

![Code_RvRkjVl4gO](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/a7f82db3-fe09-462d-9ff9-e7c478f5ddbd)

**Comment by shd101wyy** [comment]
`0.8.1` 应该修复了。抱歉！

**Comment by van-lee-fxp** [comment]
太好了，感谢开发者的及时修复~今天升级到最新版本试了一下，已经正常显示了。
