### ISSUE TITLE
Checkboxes not getting rendered beyond level 2

### ISSUE THREAD

**Issue by juergen3000** [shd101wyy/vscode-markdown-preview-enhanced#1805]
**Describe the bug**
Nested Checkboxes in Lists are not working beyond level 2:
```
- [ ] level 1 works
  - [ ] level 2 works as well
    - [ ] level 3 doesn't work
```
**Environment**
- OS: Arch Linux
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**
Show preview for markdown file containing:
```
- [ ] level 1 works, is rendered as checkbox
  - [ ] level 2 works as well, is rendered as checkbox
    - [ ] level 3 doesn't work, is rendered as - [ ]
```

**Expected behavior**
The following Markdown should show 3 Checkboxes in Preview:
```
- [ ] level 1
  - [ ] level 2
    - [ ] level 3
```

**Screenshots**
![markdown_preview_enhanced_checkboxes](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/8521405/9b43f548-316a-487a-9ca1-64e8a8b2d910)

**Comment by shd101wyy** [comment]
Should be fixed in `0.8.1`. Sorry for the trouble.
