### ISSUE TITLE
[BUG] Garbled code when generating PDF file in GB-2312

### ISSUE THREAD

**Issue by Grantley-W** [shd101wyy/vscode-markdown-preview-enhanced#1807]
**Describe the bug**

**Environment**
- OS: Windows 11
- VSCode: 1.81.0
- Markdown Preview Enhanced: 0.7.0

**To Reproduce**
When using GB-2312 to write markdown file , unable to generate PDF file with correct Chinese character

**Screenshots**

![e0d5fe7b4c0799ae969ce123f191196](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/103912927/da111d5e-94c3-4f44-95fe-9af660e3ec43)

**Additional context**

**Comment by shd101wyy** [comment]
能不能发一下 markdown 文件？谢谢

**Comment by Grantley-W** [comment]
> 能不能发一下 markdown 文件？谢谢

就是一个普通的用GB2312编码的markdown文档，在生成pdf时都有乱码的问题QAQ

**Comment by shd101wyy** [comment]
换成 utf 还是 unicode 啥的试试？我记得 gb 的那个编码很旧了？

要不然就是浏览器没有找到相应的字体

**Comment by Grantley-W** [comment]
OK，换成UTF-8以后就正常显示了
