### ISSUE TITLE
[BUG] Can not display the preview to the side

### ISSUE THREAD

**Issue by sipadan2003** [shd101wyy/vscode-markdown-preview-enhanced#1809]
**Describe the bug**
Can not display the preview to the side.

**Environment**
- OS: Windows 10
- VSCode: 1.80.2
- Markdown Preview Enhanced: 0.8.1

**To Reproduce**
1. Push [Ctrl]+[K] and [V] is down
2. Error "command 'markdown-preview-enhanced.openPreviewToTheSide' not found" is occurred and Preview is not displayed.

**Expected behavior**
Open preview to the Side.

**Screenshots**
(none)

**Additional context**
(none)

**Comment by sipadan2003** [comment]
After updated VSCode to 1.83.0, the problem was solved.
Thank you.

**Comment by shd101wyy** [comment]
Glad to hear that.
Yeah, 1.82.0 has some problems with the webview.
