### ISSUE TITLE
[BUG] vscode-markdown-preview-enhanced 0.8.x is incompatible with vscode 1.81.x

### ISSUE THREAD

**Issue by cobolbaby** [shd101wyy/vscode-markdown-preview-enhanced#1813]
**Describe the bug**
No response when clicking `Markdown Preview Enhanced:open preview to side` in the menu bar.

**Environment**
- OS: Ubuntu16.04
- VSCode: 1.81.1
- Markdown Preview Enhanced: 0.8.x

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by shd101wyy** [comment]
I actually don't know why this happened. I am using 1.82.0. Can you try upgrading your vscode?

**Comment by cobolbaby** [comment]
Vscode no longer supports ubuntu 16.04 starting from version 1.82.x.

Ref: https://github.com/microsoft/vscode/issues/193086

**Comment by GrainRainy** [comment]
i have the same question.

**Comment by shd101wyy** [comment]
I just released 0.8.3. I am not sure if this helps. I reduced the requirement of VSCode to 1.78.0. Before, it was 1.80.0

**Comment by cobolbaby** [comment]
It doesn't work.

**Comment by APJifengc** [comment]
In DevTools it shows that:

```
Activating extension 'shd101wyy.markdown-preview-enhanced' failed: structuredClone is not defined
```

It seems that `structuredClone` was added in [Node 17](https://developer.mozilla.org/en-US/docs/Web/API/structuredClone#browser_compatibility), while VSCode's Node version is 16.17.1, so it doesn't work.

**Comment by shd101wyy** [comment]
Okay let me try downgrade node.js version.

**Comment by shd101wyy** [comment]
The problem with node16 is that its LTS already ended.  
May I ask why you guys don't just upgrade your vscode?

**Comment by cobolbaby** [comment]
While we do have an upgrade plan in place, we need to coordinate a suitable timeframe due to the number of machines requiring upgrades and our recent workload.

**Comment by shd101wyy** [comment]
我看了下。我应该是无法 downgrade 到 nodejs 16 :joy: ，因为现在的一些依赖需要 nodejs 18。只能说你们自己升级到 1.82.0 了。

**Comment by shd101wyy** [comment]
我周六争取放一个版本支持 1.70.0。应该会写好了

**Comment by shd101wyy** [comment]
Okay 0.8.6 should fix this issue now. Thanks

**Comment by cobolbaby** [comment]
感谢，已经验证通过．

不过我没太看明白新版为什么会出现这个问题，以及怎么解决的，能否解解惑？

**Comment by shd101wyy** [comment]
vega-lite 这个依赖的问题，里面使用了 structuredClone，但是 vscode 1.82.0 以下版本使用的 node.js 16 不支持 structuredClone。
所以我添加了 structuredClone 的 polyfill，然后修改了一下 vega-lite 的代码。这样就没问题了。
