### ISSUE TITLE
Reveal: Visual Studio Code Build in preview is one slide ahead of editor

### ISSUE THREAD

**Issue by Sdaniele** [shd101wyy/vscode-markdown-preview-enhanced#1814]
Since the last update three days ago ([0.8.1] the currently shown slide in the build in preview is one slide ahead of the text position of the editor. 

I see it on 
Visual Studio Code
Version: 1.83.0 (Universal)
MacOS Ventura

**Comment by shd101wyy** [comment]
Thanks @Sdaniele , the issue should be fixed in version `0.8.2`. Please let me know if there is any other bugs :+1:

**Comment by Sdaniele** [comment]
thanks!!!
