### ISSUE TITLE
Regression: Reveal slide does not parse first line correctly

### ISSUE THREAD

**Issue by Sdaniele** [shd101wyy/vscode-markdown-preview-enhanced#1818]
Regression: broken in 0.8.2

The first line after the 

```
<!-- Slide...
```

is not parsed properly

For example if the line below the `<!-- Slide` is a headline it is not displayed as such.
Adding an empty line fixes that, but obviously breaks backward compatibility with older documents

**Comment by shd101wyy** [comment]
It needs to be `<!-- slide` but not `<!-- Slide`.  
It's case sensitive.

**Comment by shd101wyy** [comment]
Oh I see. Even changing it to `<!-- slide` will not work. Yes you are right. It now requires an extra line below `<!-- slide`

**Comment by shd101wyy** [comment]
Should be fixed in 0.8.3. Thanks
