### ISSUE TITLE
[BUG] The bottom semi transparent bar blocks the horizontal movement bar

### ISSUE THREAD

**Issue by cjyyx** [shd101wyy/vscode-markdown-preview-enhanced#1822]
**Describe the bug**

The bottom semi transparent bar blocks the horizontal movement bar

**Environment**
- OS: Windows 11
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**

Type a long string of formulas in the markdown, such as

```
$$
f(t) =\mathscr{L}^{-1}[F(s)]=\mathscr{L}^{-1}\left[\frac{c_{r}}{\left(s-s_{1}\right)^{r}}+\frac{c_{r-1}}{\left(s-s_{1}\right)^{r-1}}+\cdots+\frac{c_{1}}{s-s_{1}}+\frac{c_{r+1}}{s-s_{r+1}}+\cdots+\frac{c_{n}}{s-s_{n}}\right]=\left[\frac{c_{r}}{(r-1) !} t^{r-1}+\frac{c_{r-1}}{(r-2) !} t^{r-2}+\cdots+c_{2} t+c_{1}\right] \mathrm{e}^{s^{s} t}+\sum_{i=r+1}^{n} c_{i} \mathrm{e}^{s_{t} t}
$$
```

**Screenshots**

https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/50133699/f698e546-a658-4d82-becf-839f0c20521e

**Comment by shd101wyy** [comment]
Should be fixed now
