### ISSUE TITLE
[Feature Request] Support environment variables for plantuml location

### ISSUE THREAD

**Issue by NovarisOberion** [shd101wyy/vscode-markdown-preview-enhanced#1826]
**Is your feature request related to a problem? Please describe.**
I am using a relative path to plantuml based on an environmental variable (e.g. set PUML = C:\<path>\plantuml.jar.
Now I wanted to write in my config.json "${env:PUML}" to tell markdown-preview-enhanced to use the path provided in the environment variable PUML but unfortunately it does not work that way.

**Describe the solution you'd like**
Either allow plantuml.jar to be part of the PATH or allow the usage of VSCode's environmental variable syntax.

**Describe alternatives you've considered**
I tried to put the folder on the PATH but it did not work either.

**Comment by NovarisOberion** [comment]
For completeness: 
https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables

**Comment by NovarisOberion** [comment]
Nebermind, seems "${env:PUML}\\plantuml.jar" seems to work :D

**Comment by NovarisOberion** [comment]
Seems it was an artifact, it does not work :(

**Comment by shd101wyy** [comment]
Will support in next release :+1:

**Comment by shd101wyy** [comment]
Should be supported now

**Comment by NovarisOberion** [comment]
Will give it a try

**Comment by NovarisOberion** [comment]
Indeed! Many thanks for the quick update
