### ISSUE TITLE
[BUG] _underscores_ in headlines adds debug information in the preview

### ISSUE THREAD

**Issue by NovarisOberion** [shd101wyy/vscode-markdown-preview-enhanced#1827]
**Describe the bug**
When using underscores in the heading text the preview contains additional information about the line and the headline name.

**Environment**
- OS: Windows 10
- VSCode: 1.84.0-insider
- Markdown Preview Enhanced: 0.8.4

**To Reproduce**
Use the following markdown text:
```
# Test

## The _Real_ Deal

Lorem Ipsum
```

**Expected behavior**
The content within the curly braces should not be visible.

**Markdown file**
See above

**Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/75470954/a007835e-2d98-40e9-ab64-76be1c1befac)

**Comment by NovarisOberion** [comment]
On a side note: In version 0.6.10 this worked

**Comment by shd101wyy** [comment]
Should be fixed now.

**Comment by NovarisOberion** [comment]
Confirmed
