### ISSUE TITLE
[BUG] the preview pane automatically opens

### ISSUE THREAD

**Issue by quamis** [shd101wyy/vscode-markdown-preview-enhanced#1829]
**Describe the bug**
Since version 0.8, when I open a .md file, the preview pane automatically opens. This is annoying, I don't always need to see the preview

**Environment**
- OS: Linux Mint
- VSCode: 1.83.0
- Markdown Preview Enhanced: 0.8.0 - 0.8.5

**To Reproduce**
1. Open any markdown file.
2. Wait 1-2 seconds
3. The preview pane will open, even if I didn't click the preview button

**Expected behavior**
The preview should not open automatically

**Comment by shd101wyy** [comment]
We don't really have this feature unless you enabled the `markdown-preview-enhanced.automaticallyShowPreviewOfMarkdownBeingEdited".  

Did you install any other extension which automatically opens the preview?

**Comment by quamis** [comment]
Yeah, my bad. 
Seems like automaticallyShowPreviewOfMarkdownBeingEdited was somehow enabled. I don't remember doing that though, but I did test a some markdown-related extensions.

**Comment by shd101wyy** [comment]
No worries. Feel free to let us know if you any other questions 😉
