### ISSUE TITLE
[BUG] @import “*.mermaid”未渲染

### ISSUE THREAD

**Issue by iceriny** [shd101wyy/vscode-markdown-preview-enhanced#1832]
- **问题**
    - 导入的mermaid文件显示代码文本，不显示渲染图。

- **环境**
    - OS: Windows 11
    - VSCode: 1.82.1
    - Markdown Preview Enhanced: 0.8.5

- **截图**
![Snipaste_2023-10-12_19-43-40](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/54878570/93cab6b5-00f9-4e65-a6ec-b7d15c26cd9c)

**Markdown 文件**
[Desktop.zip](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/12882109/Desktop.zip)

**Comment by shd101wyy** [comment]
哦对这是个 bug。我争取看看明天能不能有时间修复一下。谢谢

**Comment by iceriny** [comment]
）））
客气！感谢工作！

**Comment by shd101wyy** [comment]
今天没修完。我估计周六可以修好。

**Comment by shd101wyy** [comment]
0.8.6 应该已经修好了
