### ISSUE TITLE
[BUG] Underscore disappears from header id

### ISSUE THREAD

**Issue by hirahara2021** [shd101wyy/vscode-markdown-preview-enhanced#1833]
**Describe the bug**
Underscore disappears from header id in 0.8.5

**Environment**
- OS: Windows 10
- VSCode: 1.83.1
- Markdown Preview Enhanced: 0.8.5

**To Reproduce**
1. test.md `#test_test_test`
2. 0.8.5 -> `test.html#testtesttest`
3. 0.8.4 -> `test.html#test_test_test`

Thank you for your kindness

**Comment by shd101wyy** [comment]
Hi @hirahara2021 , the bug should be fixed now.

**Comment by hirahara2021** [comment]
I checked that it is fixed. Thank you for your kindness.
