### ISSUE TITLE
[BUG] Imported CSV is not previewed in tabular format

### ISSUE THREAD

**Issue by r-sugishita-cosmo** [shd101wyy/vscode-markdown-preview-enhanced#1834]
**Describe the bug**
Imported CSV is not previewed in tabular format.

**Environment**
- OS: Windows 10
- VSCode: 1.83.1
- Markdown Preview Enhanced: 0.8.5

**To Reproduce**
1. Create a csv file as "sample.csv".
2. Create a md file.
3. Write the sentence `@import "sample.csv"` in the md file.
4. Open Preview.

**Expected behavior**
CSV contens shown tabular format.

**Comment by shd101wyy** [comment]
Yes it's a bug. Will fix soon.

**Comment by shd101wyy** [comment]
Hi @r-sugishita-cosmo , the bug should be fixed now.

**Comment by r-sugishita-cosmo** [comment]
Thanks for the quick fix. I was able to confirm that it was fixed.
