### ISSUE TITLE
[BUG] font-awesome not rendering

### ISSUE THREAD

**Issue by Bavarian-Barbarian** [shd101wyy/vscode-markdown-preview-enhanced#1836]
**Describe the bug**

i am/was using a local installation of font-aweseome, importing it in my style sheet using
`@import "assets/fontawesome-free-6.4.2-web/css/all.css";`

until i updated the addin today, it did work. 
Today i updated and some icons disappeared.

e.g.
:fa-canadian-maple-leaf: -> does not work
:fa-pagelines: -> works

i noticed, you're using the `font-awesome.min.css`.
is there a possibility to use `font-awesome.css`
or make it work again, that my local installation works?

**Environment**
- OS: Windows 11
- VSCode: 1.79.0
- Markdown Preview Enhanced: 0.8.6

**To Reproduce**
see above

**Expected behavior**
:fa-canadian-maple-leaf: -> does not work

**Markdown file**
Please attach the markdown file that can reproduce the bug.

**Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/74853952/32107b0d-daba-4988-8c50-db816b59ab3e)
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/74853952/a3a3d577-fdec-476b-9841-8a2757a8f7d0)

**Additional context**

**Comment by Bavarian-Barbarian** [comment]
It seems like the tool only support V4 of Font-Awesome.

and my offline installation does not work anymore because of the following changes (i guess):

[https://github.com/shd101wyy/crossnote/commit/c3bd85e2222486cebcbeffaa7c63d80ba033b3b5](https://github.com/shd101wyy/crossnote/commit/c3bd85e2222486cebcbeffaa7c63d80ba033b3b5)

`src/custom-markdown-it-features/emoji.ts`

Seems like there is a check for V4 items defined in `fontawesome4`

is there any chance i can use V6 of font-awesome again?

Thanks!

**Comment by shd101wyy** [comment]
Hi there. Yes I will take a look next week. Thanks!

**Comment by shd101wyy** [comment]
Oh yeah sorry I forgot to mention that I have updated fontawesome to the latest version 6, so you don't need to import the CSS file yourself anymore.
