### ISSUE TITLE
[BUG] URL fragments on image links do not load

### ISSUE THREAD

**Issue by suminosin** [shd101wyy/vscode-markdown-preview-enhanced#1837]
**Describe the bug**
`![]()` image link with a URL fragment will result in the following error message

```
EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open 'FILE PATH\xxxx.svg#URL_fragment'
```
**Environment**
- OS: Windows 10
- VSCode: 1.83.1
- Markdown Preview Enhanced: 0.8.6

**To Reproduce**
If the following description is used, the image will be displayed.

```
![Success](xxxxxx.svg#URL_fragment) Some text
```

If you write as follows, an error will occur.

```
![Failure](xxxx.svg#URL_fragment)
```

or

```
![Failure](xxxx.svg#URL_fragment)
Any text
```

Thanks for reading.

**Comment by shd101wyy** [comment]
Should be fixed now

**Comment by suminosin** [comment]
Thank you.
