### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by pengkunkunkun** [shd101wyy/vscode-markdown-preview-enhanced#1839]
预览时显示这样，没有正常显示。TypeError: Converting circular structure to JSON --> starting at object with constructor 'Object' | property '\df@tag' -> object with constructor 'Object' | property 'tokens' -> object with constructor 'Array' | ... | property 'settings' -> object with constructor 'zN' --- property 'macros' closes the circle

**Comment by shd101wyy** [comment]
这是什么？什么没有正常显示？:joy:

**Comment by BeastSenpai1919810** [comment]
@shd101wyy 
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/121651381/6bd43e86-9bea-467a-9ef5-014d2dac52aa)
问题能够复现
刚安装时能够正常使用插件
但是第二次打开md文档时, 会出现此问题

**Comment by shd101wyy** [comment]
@pengkunkunkun @BeastSenpai1919810 The bug is now fixed in `0.8.9`. Thanks
