### ISSUE TITLE
建议将header-id设为不变的唯一字符串

### ISSUE THREAD

**Issue by mphyfin** [shd101wyy/vscode-markdown-preview-enhanced#1842]
在版本0.8.7中增加了复制header-id的功能，通过import可以导入一个文件的一部分，非常实用的功能。可是这里的header-id与header的名字高度相关，文档编写中可能会对header的名字多次修改，这就改变了header-id，不便于交叉引用。是否可以考虑将文件的header-id设为一个不变的唯一字符串，这样无论文件怎么修改，都不会出现交叉引用的错误。

**Comment by van-lee-fxp** [comment]
`header-id`和`header`的名字(即标题的内容)不是一回事。Markdown可以被视作是HTML的一种“预处理语言”，`header-id`相当于相应类型header标签(`<h1>`至`<h6>`)的`id`属性，id属性的值可以和标题的文字内容不同，例如

```html
<h1 id="title">Markdown简史</h1>
```

表示一个一级标题，其文字内容是“Markdown简史”，而`id`属性为`title`.

在`Markdown Preview Enhanced`中，可以通过以下方法来为标题指定不同于其文字内容的`id`属性——

```
# Markdown简史 {#title}
```

其中大括号里的内容就是`id`属性的值。建议`id`属性可以设置为仅含有英文字母、数字和`-`的名称，这样比较好书写。设定完`id`属性，可以根据`id`属性的值导入段落而不用担心标题内容的变化。

**Comment by mphyfin** [comment]
赞。以前没发现这个用法

**Comment by shd101wyy** [comment]
谢谢！
