### ISSUE TITLE
[BUG] 在启用该插件后预览出的字体与原预览字体不同

### ISSUE THREAD

**Issue by aurawn01dawn** [shd101wyy/vscode-markdown-preview-enhanced#1844]
**Describe the bug**
- 我在启用该 Markdown Preview Enhanced 后，预览编写的 .md 内容时，在 Preview 界面的字体与我 VSCode 配置的编辑器字体不同。
- ( After enabling `Markdown Preview Enhanced`, the Font in the preview  is different from the expected Font. )

**Environment**
- OS: Debian GNU/Linux 12 
- VSCode: 1.83.1
- Markdown Preview Enhanced: 0.8.7

**Comment by shd101wyy** [comment]
这个预览本身设置的就不是和 vscode 的字体一样的。你有需求的话可以自己 `Markdown Preview Enhanced: Customize Css`: https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/customize-css

或者把 preview theme 设置为 `None` 看看行不行？
