### ISSUE TITLE
incorrect in-line code parsing [BUG] 

### ISSUE THREAD

**Issue by josefdostal** [shd101wyy/vscode-markdown-preview-enhanced#1848]
**Describe the bug**

**Environment**
- OS: Windows 11
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.8.7

**To Reproduce**
1. write somthing like: 
```md
   ```example```: let's see what happens
```
3. in the preview is rendered: 
<img width="310" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/36886044/8ec338c9-5564-4400-a31f-8095c3ae37bb">

4. and any following codeblock doesn't end. So when my MD code looks like this:  

```md
# title

```example```: let's see what happens

```json
{
    "message": "hi, there"
}
`` `

Hello 
```

Following is rendered:
<img width="746" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/36886044/6321f770-7ee0-4b7c-981c-a525e3ca855e">

**Expected behavior**
Not to write the {data-source...}  tag
Not to mess up other code blocks

**Markdown file**
[example.md](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/13052466/example.md)
bug.

**Screenshots**
See above

**Additional context**
This issue appers all the way in 0.8 version. Not in 0.7.10

**Comment by shd101wyy** [comment]
Should be fixed.
