### ISSUE TITLE
[BUG] @import 引入文件時，如果文件名中含有空格會無法引入該文件。

### ISSUE THREAD

**Issue by Soanguy** [shd101wyy/vscode-markdown-preview-enhanced#1857]
最新版本的MPE中，使用 @import 引入是文件名中無法含有【空格】，但是之前在使用舊版——應該是 0.6.X 的版本中不會出現這種情況。

> 另外，似乎最新版本會自動吞掉文件中存在的空格。我使用下面的這個含有空格的文件名，但是在引入時：如果引入的代碼中不包含空格，會正常顯示。但是一旦按照源文件名使用空格，則無法正常顯示。

源文件名：

<img width="226" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/24608949/035523fa-b00a-4b0d-8a51-a99bb540da1c">

含有空格的引入和預覽：

<img width="399" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/24608949/e6eb8de5-adc5-46ed-8be0-128df6ba625a">

<img width="700" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/24608949/b64d0845-c0da-4db0-98d2-8ffdac76a000">

不含有空格的引入和預覽：

<img width="426" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/24608949/76066e3c-6f47-47be-af1e-a2d6283fdb55">

<img width="345" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/24608949/4de9f6de-c11f-44ca-8276-d1392f518308">

**Comment by shd101wyy** [comment]
ok 我这周有时间了看一下

**Comment by shd101wyy** [comment]
The issue should be fixed now in `0.8.10`. Thanks

**Comment by irs-alba1** [comment]
Unbelievable reaction time! Thank you very much!
I can confirm it is working again with 0.8.10
