### ISSUE TITLE
[BUG] Markdown default editor setting cannot be saved

### ISSUE THREAD

**Issue by tccrabyoguy** [shd101wyy/vscode-markdown-preview-enhanced#1860]
**Describe the bug**
```
  "workbench.editorAssociations": {
    "*.md": "default"
  }
```
I configured the markdown editor as default , but it is deleted automatically when I restart the VS Code. 
When I disabled the MPE extention, it is work correctly. Please fix it. Thanks!

<img
  src="https://user-images.githubusercontent.com/26083253/277237784-7f6fe91c-30ee-43c1-a194-f46647e3bc2e.png"
  alt="before" />

<img
  src="https://user-images.githubusercontent.com/26083253/277237879-db4c4572-20c6-4d43-9126-5370e561c2de.png"
  alt="after" />

**Environment**
- OS: Windows 11
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**

**Expected behavior**

**Markdown file**
Please attach the markdown file that can reproduce the bug.

**Screenshots**

**Additional context**

**Comment by shd101wyy** [comment]
Should be fixed now in `0.8.10`. Thanks
