### ISSUE TITLE
[BUG] How to use 'require("package")' in the "parser.js"?

### ISSUE THREAD

**Issue by leoli0605** [shd101wyy/vscode-markdown-preview-enhanced#1863]
**Describe the bug**
Is there any example how to use 'require()' or 'import()' in the parser.js file?
For example, below is what I want, but it's not work ... please help me how to fix it?, thanks.

```javascript
var md = require("markdown-it")().use(require("markdown-it-multimd-table"));

({
  // Please visit the URL below for more information:
  // https://shd101wyy.github.io/markdown-preview-enhanced/#/extend-parser

  onWillParseMarkdown: async function (markdown) {
    return md.render(markdown);
    // return markdown.replace(/#+\s+/gm, ($0) => $0 + "😀 ");
  },

  onDidParseMarkdown: async function (html) {
    return html;
  },
});
```

**Comment by shd101wyy** [comment]
`require` is not supported because this extension also run on web like https://vscode.dev where node.js module is not available.  

I can add `markdown-it-multimd-table` for you in next release.
