### ISSUE TITLE
[BUG] command 'markdown-preview-enhanced.openPreviewToTheSide' not found

### ISSUE THREAD

**Issue by Miao-Bukeyan** [shd101wyy/vscode-markdown-preview-enhanced#1866]
预览时报错“command 'markdown-preview-enhanced.openPreviewToTheSide' not found”，请问为什么。谢谢

**Environment**
- OS: Windows 11
- VSCode: 1.69.2
- Markdown Preview Enhanced: 0.8.4

**Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/19161045/d5390eae-2230-40c9-a87e-1e383285dc83)

**Comment by shd101wyy** [comment]
vscode 版本太低

**Comment by shd101wyy** [comment]
而且你用的也不是最新版的插件
