### ISSUE TITLE
[BUG] plantuml 在最新版本中必須說明絕對路徑或者網絡引用，但在舊版本中無需如此

### ISSUE THREAD

**Issue by Soanguy** [shd101wyy/vscode-markdown-preview-enhanced#1868]
**Describe the bug**

在舊版本 0.6.x 中，安裝了 plantuml 之後，可以自動引用 plantuml 的安裝位置。但是在最新版本中，必須要引用絕對位置或者從網絡上引用。

我目前通過 homebrew 安裝的 plantuml ，他的路徑如下：

`/opt/homebrew/Cellar/plantuml/1.2023.11/libexec/plantuml.jar`

如果引用絕對路徑的話，隨着版本的更新不就需要每次重新填寫 plantuml 的絕對路徑麼。不知道是否可以跟舊版本一樣自動尋找他的安裝路徑？

**Environment**
- OS: macOS
- VSCode: 1.83.1
- Markdown Preview Enhanced: 0.8.10

<img width="452" alt="image" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/24608949/5f37b02b-7842-47d9-88bc-a88f1ee8f96b">

**Comment by shd101wyy** [comment]
旧版本是因为自带一个 plantuml.jar 文件，所以不需要自己设置路径。现在的版本因为要支持 https://vscode.dev 这种 vscode for web 所以移除了自带的 plantuml.jar。

hmm 我能想的解决方案目前就是我以后支持个 vscode command 然后用户通过这个 vscode command 来下在 plantuml.jar 放在一个位置，然后插件自动设置路径到这个 jar :thinking:

**Comment by Soanguy** [comment]
這樣似乎有點小麻煩。還是保留目前的絕對路徑或者網絡引用吧。只要不經常更新這些就好 👍
