### ISSUE TITLE
[BUG] Environment variable in configPath not working?

### ISSUE THREAD

**Issue by changbowen** [shd101wyy/vscode-markdown-preview-enhanced#1869]
## Environment variable in configPath not working?

I have set this:
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/15975872/56959510-c204-4c61-bf9b-cf1fae574058)

Yet folders like this is created each time I open vscode and a md file:
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/15975872/195f9f3a-d0ab-439e-af7e-621d1e55fe0b)

VS Code is portable (using data folder under app root). Don't know if that makes a difference.

**Environment**
Version: 1.83.1
Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
Date: 2023-10-10T23:48:05.904Z (2 wks ago)
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045
Markdown Preview Enhanced: 0.8.10

**Comment by shd101wyy** [comment]
You need to write env variables as `${env:ENV_VARIABLE}`

https://code.visualstudio.com/docs/editor/variables-reference#_environment-variables

**Comment by changbowen** [comment]
Sorry but I tried that as well.. The CSS is not being loaded and if I do `Markdown Preview Enhanced: Customize CSS (Global)`, it tries to open this path and shows an error:
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/15975872/c2d00990-eacb-4198-af1e-c22aed3246b4)
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/15975872/6764d5a7-e94e-4cd9-9c2e-494a0b596ffd)
