### ISSUE TITLE
[Feature Request] Option to hide reading time estimation

### ISSUE THREAD

**Issue by bunnyhero** [shd101wyy/vscode-markdown-preview-enhanced#1877]
**Is your feature request related to a problem? Please describe.**
I find the reading time estimation in the preview footer distracting and would like to be able to hide it.

**Describe the solution you'd like**
A simple on-off toggle to disable the reading time estimation.

**Describe alternatives you've considered**
I've looked for an existing toggle but I couldn't find one, if it exists. I've also considered figuring out how to add custom CSS to hide this. 

**Additional context**
I just like having as few distractions as possible. Thank you.

**Comment by shd101wyy** [comment]
https://github.com/shd101wyy/vscode-markdown-preview-enhanced/releases/tag/0.8.11

Zen mode is added.

**Comment by bunnyhero** [comment]
Thank you! It's perfect.
