### ISSUE TITLE
[Feature Request] 请保留一个“纯净”预览

### ISSUE THREAD

**Issue by wxy** [shd101wyy/vscode-markdown-preview-enhanced#1879]
首先，非常感谢作者做出这么功能丰富的预览界面。
不过，在我的使用场景中，有时候只是需要一个渲染成纯 HTML 的页面，我只需要全选复制，用在其它地方即可。而预览页面过多的按钮、菜单，不但造成麻烦，而且我发现由于有鼠标移动到某个区块是，会显示浮动的绿色按钮，我全选复制时，在代码中就会有个 `<button>` 元素，需要小心找到删除。
所以，我想应该有一个选项，可以只看纯 HTML 渲染结果，没有任何相关按钮、下拉菜单等等。
当然，最好在生成的 HTML 也不要有什么 class 和 id 之类。
请作者考虑。

**Comment by shd101wyy** [comment]
https://github.com/shd101wyy/vscode-markdown-preview-enhanced/releases/tag/0.8.11

0.8.11 添加了禅模式

**Comment by wxy** [comment]
非常感谢您的努力！我想如果有可能的话，我将来也会参与开发贡献，而不只是提出功能需求。
为您的工作点赞！
