### ISSUE TITLE
newlines are converted into `<br/>`. This is not compliant markdown.

### ISSUE THREAD

**Issue by arabidopsis** [shd101wyy/vscode-markdown-preview-enhanced#188]
Great package guys!
but...

newlines are converted into `<br/>`.

This doesn't seem to be compliant with markdown. viz: from  https://daringfireball.net/projects/markdown/syntax#p

> When you do want to insert a <br /> break tag using Markdown, you end a line with two or more spaces, then type return.

**Comment by jabiertxof** [comment]
I also have the same problem

**Comment by jabiertxof** [comment]
uncheck break on single newlines code  preferences

**Comment by jabiertxof** [comment]
Issue can be closed @shd101wyy

**Comment by shd101wyy** [comment]
Thanks!
