### ISSUE TITLE
[BUG] vega-lite图表在`reveal.js`幻灯片中无法正常显示

### ISSUE THREAD

**Issue by van-lee-fxp** [shd101wyy/vscode-markdown-preview-enhanced#1880]
我正在使用Markdown Preview Enhanced插件的幻灯片功能来制作幻灯片，我在幻灯片中需要插入`vega-lite`图表来展示数据，但是原本在`markdown`文档中可以正常显示的`vega-lite`图表跑到幻灯片里的时候就不能正常显示了。

当我从外部导入一个`.json`文件作为`vega-lite`图表的数据时，相应的位置出现了如下错误信息：

```
SyntaxError: Unexpected number in JSON at position 3
```

而这个图表在普通的markdown文档中预览是完全没有问题的。下面两幅图分别是在`reveal.js`中和普通markdown文档中的效果

![Code_qKZ5VGwm0g](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/f1cebfc5-530f-417e-b847-c66757ef49ca)

![Code_LrRywenSX0](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/146909397/24621454-5cbf-401d-961b-8f609d7ff32b)

**Comment by shd101wyy** [comment]
应该已经修复了
