### ISSUE TITLE
[BUG] Binary content of .emf files displayed in MPE

### ISSUE THREAD

**Issue by YuruiHong** [shd101wyy/vscode-markdown-preview-enhanced#1894]
**Describe the bug**
When using pandoc to convert .docx to .md, some of the images would be generated as .emf, which are not correctly displayed in MPE. What I really think is a bug is that instead of display nothing, MPE directly put the binary contents of that .emf there, which occupies a lot of space. I would suggest hide that totally if implementing .emf rendering is out of scope.

**Environment**
- OS: Debian 6.5.13-1 x86_64
- VSCode: 1.85.0-insider
- Markdown Preview Enhanced: 0.8.10

**To Reproduce**
1. Get the markdown file refer to a .emf, which is usually achieved by converting from .docx
2. Open preview

**Expected behavior**
.emf is properly rendered or completely ignored

**Markdown file**
Please attach the markdown file that can reproduce the bug.
[emf_error.zip](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/13536982/emf_error.zip)

**Screenshots**
![Screenshot at 2023-12-03 01-55-18](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/83064277/a32efbc3-a254-4239-b23d-e9cf54a9045c)

**Comment by shd101wyy** [comment]
It seems like html doesn't support displaying `.emf` file format image. :thinking:

**Comment by YuruiHong** [comment]
I did not expect `.emf` to be rendered since it's not supported by HTML either. Now, it seems the binary display has been miraculously removed without commits referencing this.😂

**Comment by shd101wyy** [comment]
It's fixed by this commit: https://github.com/shd101wyy/crossnote/pull/348/commits/0bccb45040bd4d99f8c3187d3d9bb9b94515bcc1#diff-c7ea895dcb3136397bd7f0ff8abc4a28b63982e0d331bb358f197e9789b63545R698
