### ISSUE TITLE
扩展“shd101wyy.markdown-preview-enhanced”使用了 "vscode.previewHtml" 命令

### ISSUE THREAD

**Issue by yxksabri** [shd101wyy/vscode-markdown-preview-enhanced#192]
扩展“shd101wyy.markdown-preview-enhanced”使用了 "vscode.previewHtml" 命令，而此命令已弃用且即将删除。请针对此扩展提交问题，从而更新为使用 VS Code 的 webview API

**Comment by shd101wyy** [comment]
是的我会在这周末发个新版本修复这个问题。

**Comment by jiangxiaobai1989** [comment]
> 是的我会在这周末发个新版本修复这个问题。谢谢！

感谢。今天用起来发现不能实时预览了，把我急死了。哈哈
Thanks. It will affect the function of realtime preview. It troubles me a lot. Haha.

**Comment by yxksabri** [comment]
> 是的我会在这周末发个新版本修复这个问题。谢谢！

**Comment by shd101wyy** [comment]
等修完了再关吧

**Comment by ShusenTang** [comment]
> > 是的我会在这周末发个新版本修复这个问题。谢谢！
> 
> 感谢。今天用起来发现不能实时预览了，把我急死了。哈哈
> Thanks. It will affect the function of realtime preview. It troubles me a lot. Haha.


同样的问题

**Comment by shd101wyy** [comment]
我刚发了个新版本 0.3.12。
各位可以试一下，应该是修复了 previewHtml 的问题了。但是可能会出现新的 bug 因为我改了好多代码。。。
如果发现新问题请再 post 上来哈多谢🙏

**Comment by ShusenTang** [comment]
> 我刚发了个新版本 0.3.12。
> 各位可以试一下，应该是修复了 previewHtml 的问题了。但是可能会出现新的 bug 因为我改了好多代码。。。
> 如果发现新问题请再 post 上来哈多谢🙏

新版本还是不能实时预览。

**Comment by shd101wyy** [comment]
怪哉 😱
我先去吃饭了意识有点模糊了😰
你重启下编辑器试试？

**Comment by over-shine** [comment]
It works correctly now. Thank you very much!

**Comment by ShusenTang** [comment]
> 怪哉 😱
> 我先去吃饭了意识有点模糊了😰
> 你重启下编辑器试试？

我的锅，重启vscode就正常了，issue可以关了。

**Comment by zcc0721** [comment]
更新了之后问题解决了，感谢！此 issue 可以关闭了。

**Comment by yxksabri** [comment]
确实好了
