### ISSUE TITLE
[BUG] toml code block support is not very good

### ISSUE THREAD

**Issue by zonglin-hub** [shd101wyy/vscode-markdown-preview-enhanced#1920]
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/87891147/f43150b0-8181-4f8d-9ad5-71cc567633bf)
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/87891147/643597e9-edd0-41b5-b9a2-09ca1c28ad9b)

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks.
