### ISSUE TITLE
[BUG] If URL encoding is used, the preview cannot be displayed.

### ISSUE THREAD

**Issue by suminosin** [shd101wyy/vscode-markdown-preview-enhanced#1934]
**Describe the bug**
If URL encoding is used, the preview cannot be displayed.

**Environment**
- OS: Windows 10
- VSCode: 1.84.2
- Markdown Preview Enhanced: v0.8.11

**To Reproduce**
In the example below, the preview is not displayed with the message "SomeThing is wrong. Please close and open the preview again."

```
1. [An error occurs](http://videoinfo.tenchi.ne.jp/?DirectShow%20File%20Reader%20%A5%D7%A5%E9%A5%B0%A5%A4%A5%F3%20for%20AviUtl)

2. [Not a problem](https://e-words.jp/w/URL%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%89.html#:~:text=URL%E3%82%A8%E3%83%B3%E3%82%B3%E3%83%BC%E3%83%89%EF%BC%88URL%20encoding%EF%BC%89%E3%81%A8,%E3%81%AB%E3%82%88%E3%81%A3%E3%81%A6%E8%A1%A8%E8%A8%98%E3%81%99%E3%82%8B%E5%A4%89%E6%8F%9B%E8%A6%8F%E5%89%87%E3%80%82)
```

Not all URL encodings result in errors.
Sometimes the URL encoding that causes the error can be displayed.
However, pressing the refresh button in the preview area or previewing again with `Ctrl+k, v` will cause the error again.

**Markdown file**
[error_sample.md](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/14274600/error_sample.md)

**Screenshots**
![2024-02-14-11-28-19](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/112995163/f273f0a1-5043-4983-8de3-928b2e75c06a)

Thank you for reading.

**Comment by shd101wyy** [comment]
It seems like the first URL is malformed. I will fix this in the new release today.

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks.

**Comment by suminosin** [comment]
Thank you. It was really helpful.
