### ISSUE TITLE
[BUG] #tag is treated as Header 1

### ISSUE THREAD

**Issue by thomastthai** [shd101wyy/vscode-markdown-preview-enhanced#1937]
**Describe the bug**
A tag like #todo is rendered in the preview as an H1 header.

**Environment**
- OS: Windows 11
- VSCode: 1.82.0
- Markdown Preview Enhanced: 0.8.0

**To Reproduce**
1. Type `#todo` in a markdown document
2. Render the preview, i.e., press Ctrl+k, v
3. `#todo` is rendered as an H1

**Expected behavior**
A markdown heading starts with one or more `#` followed by a `space` and then the heading title. Since `#todo` didn't have a `space`, it should not have been considered a heading.

![#todo tag](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/16532581/36ae207a-9016-4210-a04a-d7b23b33e400)

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks.
