### ISSUE TITLE
[BUG] All half-width quotation marks are converted to full-width quotation marks | 所有半角引号都转换为全角引号

### ISSUE THREAD

**Issue by xixu-me** [shd101wyy/vscode-markdown-preview-enhanced#1949]
**Describe the bug**
All half-width quotation marks are converted to full-width quotation marks!

**Environment**

- OS: Windows 11
- VSCode: 1.86.2
- Markdown Preview Enhanced: 0.8.11

**Markdown file**

```markdown
# Site Map

- Xi Xu's Home Page
    > <https://xi-xu.me>
- Xi Xu's Blog Posts
    > <https://blog.xi-xu.me>
- Xi Xu's File List
    > <https://file.xi-xu.me>
- Xi Xu's V2*** Documentation
    > <https://v2.xi-xu.me>  
- Xi Xu's More Things
    > <https://more.xi-xu.me>
```

**Screenshots**

![](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/109734945/7ec8b508-8fcd-4ba0-90e2-4f23b18916f0)

**Comment by van-lee-fxp** [comment]
引号实际上是没有全半角之分的，正式的中文和英文文本中的引号用的是同样的字符

* `“` 是左双引号，`”` 是右双引号
* `‘` 是左单引号，`’` 是右单引号
* `'` 和 `"` 是ASCII字符中的引号，也被称为“直引号”或“傻瓜引号”，是没有左右之分的。编程中所使用的就是这种引号。但是，在正式的文章和文件中，不论中文还是西文，都不建议使用这种引号。关于这个问题可以参考B站`@oooooohmygosh`的视频：`https://www.bilibili.com/video/BV1wd4y1T73v`

Markdown Preview Enhanced 中的 Enable Typographer 这个功能，就提供了一个对引号的的自动转换，将直引号根据其所在的位置进行转换。如果你觉得预览效果中引号的宽度偏宽，可能是字体的原因。你可以通过修改样式表来更换字体。例如——

```less
body {
    font-family: "Ysabeau", "LXGW Wenkai";
}
```

**Comment by xixu-zg** [comment]
原来如此，涨知识了，谢谢！
