### ISSUE TITLE
[Feature Request] 如何关闭标题罗马数字preview

### ISSUE THREAD

**Issue by vzhentian97** [shd101wyy/vscode-markdown-preview-enhanced#1956]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
preview会出现罗马数字

**Describe alternatives you've considered**
我想在preview时我写啥就展示啥

**Additional context**
<img width="368" alt="Snipaste_2024-03-07_10-33-48" src="https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/38022237/b66523de-cf5a-4c12-bd56-108354f76cc8">

**Comment by van-lee-fxp** [comment]
这个是取决于样式表的。你可以在样式表中改变`ol`对象的`list-style-type`属性

例如——

```less
ol ol {
    list-style-type: decimal;
}
```
