### ISSUE TITLE
[BUG] latex公式没有被渲染

### ISSUE THREAD

**Issue by Guo-Chenxu** [shd101wyy/vscode-markdown-preview-enhanced#1978]
**Describe the bug**
latex公式没有被渲染

**Environment**
- OS: Windows 10
- VSCode: 1.87.2
- Markdown Preview Enhanced: 0.8.13

**To Reproduce**
如下的一个latex公式
```
$r \times s = \{ tq | t \in r \  and \ q \in s \}$
```
此时打开mpe预览, 可以看到公式并没有被渲染
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/90923304/bd1cb52c-0597-4b8b-8a0a-caf8d9ad9e07)

**Expected behavior**
期望公式被正常渲染, 如下:

$r \times s = \{ tq | t \in r \  and \ q \in s \}$

**Markdown file**
```
$r \times s = \{ tq | t \in r \  and \ q \in s \}$
```

**Screenshots**
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/90923304/7fc43e23-bc10-4ef3-8593-5881f9bd2e60).

**Additional context**
导出的pdf中也没有渲染, 似乎是近期版本才出现的问题

**Comment by van-lee-fxp** [comment]
你使用的是LaTeX渲方式KaTeX还是MathJaX？

**Comment by Guo-Chenxu** [comment]
> 你使用的是LaTeX渲方式KaTeX还是MathJaX？

上面的问题是用katex下出现的, 我切换到mathjax又试了一下, 在mathjax下预览时公式可以正确预览
![正确预览](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/90923304/49548ed4-7977-4eea-a3a7-e2a1be0efa9b)

但是按照下面方式导出pdf后, 在pdf中不会显示公式内容
![导出方式](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/90923304/afb7eaf4-ebd1-4b7a-baa7-31d22e91d103)
![无公式显示](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/90923304/b800a06a-6a62-45a7-b70a-4136ac570217)


我以前没有改过这个参数, 所以以前应该一直都是katex的渲染方式, 我也试过降低版本但是也没有解决这个问题.

![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/90923304/359a68a0-429d-4fd9-bd01-15416d43fd99)

不过我又尝试了选择`none`这个选项, 目前是能够正确预览和导出的, 所以我猜想会不会是和我本机安装的一些东西冲突导致的 (最近刚安装了MiKTeX, 而且用其他插件比如markdown pdf导出也是无法正确缺渲染公式)

**Comment by van-lee-fxp** [comment]
你是用Chrome Puppeter导出的吗？

**Comment by van-lee-fxp** [comment]
如果是的，这可能是因为MathJax的脚本处理公式需要一定的时间，你可以给Chrome Puppeter设置一个导出延时，或者选择用浏览器打开，然后在浏览器中等待公式渲染完毕后，点击打印，选择保存为PDF

**Comment by Guo-Chenxu** [comment]
> 如果你是用Puppeter导出的，这可能是因为MathJax的脚本处理公式需要一定的时间，你可以给Chrome Puppeter设置一个导出延时，具体方法是更改一个名为`markdown-preview-enhanced.puppeteerWaitForTimeout`的设置项（单位为毫秒），然后选一个合适的值，大约3000 - 5000左右。或者选择用浏览器打开，然后在浏览器中等待公式渲染完毕后，点击打印，选择保存为PDF

太感谢了, 目前看来是没有问题了, 设置了延时以后用mathjax也可以正常导出了
