### ISSUE TITLE
[Feature Request] 编辑栏与预览栏在电脑屏幕上更好地匹配

### ISSUE THREAD

**Issue by YeahyeahLiu** [shd101wyy/vscode-markdown-preview-enhanced#1984]
**Is your feature request related to a problem? Please describe.**
当我在编辑栏输入时，我希望实时在预览栏看到我输入的结果。但是实际上预览栏经常会做一些不知何意的滑动，恰好使得我编辑的片段不能被我看见。

**Describe the solution you'd like**
方案1：增加一个消除这两个区域的联动的选项，使我在对编辑栏进行输入时预览栏不要动；方案2：优化两个区域的联动方式。

![e293457a5d118c7f58042f37dad0f74](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/154450207/ed4bb9d9-22ef-4e23-9148-b74f2a146512)

这张图片是一个例子，当我在编辑最后一个标题"等体过程"下面的文字的时候，预览栏并没有把这部分内容展现出来。

**Comment by moonlitusun** [comment]
![CleanShot 2024-04-16 at 09 17 32](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/22940470/743a3f9d-b7d3-465f-b005-e01285bedde7)
Maybe you can turn it off.

**Comment by YeahyeahLiu** [comment]
thanks very much.
________________________________
发件人: moonlit ***@***.***>
发送时间: 2024年4月16日 9:20
收件人: shd101wyy/vscode-markdown-preview-enhanced ***@***.***>
抄送: YeahyeahLiu ***@***.***>; Author ***@***.***>
主题: Re: [shd101wyy/vscode-markdown-preview-enhanced] [Feature Request] 编辑栏与预览栏在电脑屏幕上更好地匹配 (Issue #1984)


CleanShot.2024-04-16.at.09.17.32.png (view on web)<https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/22940470/743a3f9d-b7d3-465f-b005-e01285bedde7>
Maybe you can turn it off.

―
