### ISSUE TITLE
表格显示错误

### ISSUE THREAD

**Issue by zcc0721** [shd101wyy/vscode-markdown-preview-enhanced#205]
表格内容为：

```
| 字段 | 字段长度 | 说明 |
| ---- | -------- | ---- |
| 交易版本     | 1-8 字节 | 当前交易版本固定为 0x01，占用一个 1 个字节 |
| time range   | 1-8 字节 |  |
| 交易输入数量 | 1-4 字节 | 交易输入列表中含有的交易输入的数量
| 交易输入列表 | 不定        |  |
| 交易输出数量 | 1-4 字节 | 交易输出列表中含有的交易输输出的数量
| 交易输出列表 | 不定   |  |
```

渲染结果：

![image](https://user-images.githubusercontent.com/17916496/54583891-a229d380-4a50-11e9-83ca-5f3e911f634f.png)

表格之间的分割线没了。

在 GitHub 中显示如下：

| 字段 | 字段长度 | 说明 |
| ---- | -------- | ---- |
| 交易版本     | 1-8 字节 | 当前交易版本固定为 0x01，占用一个 1 个字节 |
| time range   | 1-8 字节 |  |
| 交易输入数量 | 1-4 字节 | 交易输入列表中含有的交易输入的数量
| 交易输入列表 | 不定        |  |
| 交易输出数量 | 1-4 字节 | 交易输出列表中含有的交易输输出的数量
| 交易输出列表 | 不定   |  |

环境：

- macOS Mojave 10.14.3
- vscode 1.32.3
- markdown preview enhanced 0.3.13

**Comment by zcc0721** [comment]
在 GitHub 中显示如下：

![image](https://user-images.githubusercontent.com/17916496/54584596-c090ce80-4a52-11e9-80b5-1ea333c1a622.png)

**Comment by zcc0721** [comment]
在 GitHub 中显示如下：

| 字段 | 字段长度 | 说明 |
| ---- | -------- | ---- |
| 交易版本     | 1-8 字节 | 当前交易版本固定为 0x01，占用一个 1 个字节 |
| time range   | 1-8 字节 |  |
| 交易输入数量 | 1-4 字节 | 交易输入列表中含有的交易输入的数量
| 交易输入列表 | 不定        |  |
| 交易输出数量 | 1-4 字节 | 交易输出列表中含有的交易输输出的数量
| 交易输出列表 | 不定   |  |

**Comment by shd101wyy** [comment]
把插件里面的设置 enableExtendedTableSyntax 给关掉试试

**Comment by zcc0721** [comment]
@shd101wyy 关掉就可以了，谢谢。
