### ISSUE TITLE
[BUG] C# not colorized

### ISSUE THREAD

**Issue by unleashed7** [shd101wyy/vscode-markdown-preview-enhanced#2060]
C# is plain, while other languages (c, c++ etc.) work correctly, C# is not recognized, no matter what theme is used.

- OS: Windows 10
- VSCode: 1.84.0
- Markdown Preview Enhanced: v0.8.14

![Screenshot 2024-10-29 153404](https://github.com/user-attachments/assets/0016f1f7-ccdf-45d2-b95c-1508d5a72492)

**Comment by shd101wyy** [comment]
@unleashed7 Try `csharp` instead of `c#`

**Comment by shd101wyy** [comment]
````
```csharp
// ...
```
````
