### ISSUE TITLE
[BUG] ActionScript not colorized

### ISSUE THREAD

**Issue by ylazy** [shd101wyy/vscode-markdown-preview-enhanced#2063]
**Describe the bug**

Syntax highlighting for ActionScript language didn't worked.

The source markdown:

![image](https://github.com/user-attachments/assets/6fccd765-64a9-45c5-93d6-3aba553fd6fc)

Actual Result:

![image](https://github.com/user-attachments/assets/d82de990-f942-4607-86c3-5871a5e26dca)

Expected Result:

![image](https://github.com/user-attachments/assets/e3324987-63f0-46a2-b33c-2b9321bdb3d2)

**Environment**
- OS: Windows 11
- VSCode: 1.95.1
- Markdown Preview Enhanced: 0.8.14

Thanks!

**Comment by shd101wyy** [comment]
@ylazy Try `actionscript` instead of `as`.

**Comment by shd101wyy** [comment]
````
```actionscript
// ...
```
````

**Comment by ylazy** [comment]
Thank you it worked but cannot recognize the data type. Could you please fix it.

![image](https://github.com/user-attachments/assets/1c6d2757-505e-4cf4-8ffa-85c1a0662a48)

Thanks!
