### ISSUE TITLE
Please keep markdown notation of the compiled markdown

### ISSUE THREAD

**Issue by tmori3y2** [shd101wyy/vscode-markdown-preview-enhanced#21]
https://github.com/tmori3y2/MPE-Test/blame/master/vscode/import/test_import_001_.md

test_import_001_.md is the compiled markdown.

The atx headers converted into the html headers.

Of course, markdown supports html notation.

But it is the better to keep markdown notation.

Best Regards

**Comment by shd101wyy** [comment]
Okay I see.

**Comment by shd101wyy** [comment]
Fixed :)

**Comment by tmori3y2** [comment]
Thanks a lot !
