### ISSUE TITLE
Show preview on the side

### ISSUE THREAD

**Issue by PierreMarchand20** [shd101wyy/vscode-markdown-preview-enhanced#217]
I used the shortcut `cmd-k v` to open the preview on the side but it seems that it does not work anymore. Now, it only opens it in the same pane.

I also noticed that using the shortcut `cmd-shift-v` opens the built-in viewer for markdown and not the one of this extension.

**Comment by PierreMarchand20** [comment]
From what I saw, the documentation is not updated and now `cmd-k v`is the shortcut for opening the viewer and there is no shortcut for opening to the side. But why this change ? It would be nice to have a shortcut for both.

![image](https://user-images.githubusercontent.com/15056323/56883046-ccb27780-6a65-11e9-85e6-03ab61f79851.png)

**Comment by shd101wyy** [comment]
![Screenshot from 2019-05-26 18-34-57](https://user-images.githubusercontent.com/1908863/58380554-059e2780-7fe5-11e9-8c71-2260754768db.png)

Weird... This is mine on Ubuntu 18.04.

**Comment by free-adam** [comment]
I want to use cmd+k v to open MPE's preview, but always show me the default preview.
