### ISSUE TITLE
Why use this extension over the built-in markdown preview?

### ISSUE THREAD

**Issue by rcdailey** [shd101wyy/vscode-markdown-preview-enhanced#219]
I am honestly not sure why this extension should be used. By default, VS Code provides markdown preview. I can open to the side, and it also scroll-syncs. So what's the benefit?

Reason I'm asking is to confirm whether or not maybe this extension was created prior to VS Code having support for markdown preview, in which case it would make sense. But at the moment the choices are confusing.

**Comment by shd101wyy** [comment]
Yes you are right. This plugin was created prior to VSCode having support for markdown preview. It was initially designed and programmed for the Atom editor and then ported to support VSCode in 2017. Compared to the default markdown preview on VSCode, this plugin offers more functionalities such as the math typesettings, diagrams, etc.

I hope this answers your questions.

Thanks

**Comment by shd101wyy** [comment]
Yes you are right. This plugin was created prior to VSCode having support for markdown preview. It was initially designed and programmed for the Atom editor and then ported to support VSCode in 2017. Compared to the default markdown preview on VSCode, this plugin offers more functionalities such as the math typesettings, diagrams, etc.

I hope this answers your questions.

Thanks

**Comment by rcdailey** [comment]
Yes, thank you very much.
