### ISSUE TITLE
Math rendering doesn't work

### ISSUE THREAD

**Issue by lalloni** [shd101wyy/vscode-markdown-preview-enhanced#232]
I use extensively math rendering.

Before 0.4.0 it only worked using PhantomJS. All other engines just included formulas' source code literally in the rendered PDF.

Now on 0.4.0, with PhantomJS not available, I've lost all chance of working using math and this extension. And I need it ASAP... I'll try to go back to the previous version.

Is PhantomJS gone for good?

Is there any way of getting math to work with Chrome or Pandoc?

**Comment by shd101wyy** [comment]
Yes please use [puppeteer](https://shd101wyy.github.io/markdown-preview-enhanced/#/puppeteer) instead as PhantomJS is no longer maintained.

**Comment by shd101wyy** [comment]
There is also a `timeout` option in front-matter I forgot to add to the doc.
```
---
puppeteer:
    timeout: 3000 # wait for 3 seconds.
---
```

**Comment by lalloni** [comment]
@shd101wyy unfortunately using puppeteer does not work for this, when I try, it does not render math at all, inlining source code.

**Comment by shd101wyy** [comment]
May I see your markdown file? Are you using KaTeX or MathJaxfor math rendering? Thank you

**Comment by lalloni** [comment]
MathJax. [Here](https://gist.github.com/lalloni/67f842100b5c22ba253bdb97cf54856c).

**Comment by shd101wyy** [comment]
Set front-matter like this

```yaml
---
Title: Práctica Módulo 8
Author: Pablo Lalloni
puppeteer:
    timeout: 5000 # wait for 5 seconds
---
```

I got PDF successfully
[test.pdf](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/3259928/test.pdf)

**Comment by shd101wyy** [comment]
I think it is because it takes some time for MathJax to finish rendering, so you have to wait for a few seconds.

**Comment by lalloni** [comment]
Oh... so the timeout is required... let me check that.

**Comment by lalloni** [comment]
Yes, it worked, even with 1000 timeout. Great! Thanks.

**Comment by lalloni** [comment]
hey @shd101wyy, is there some way of specifying the timeout in plugin's configuration instead of document front matter?

**Comment by shd101wyy** [comment]
Ah no. You can only specify the timeout in front matter for now. I might allow you to specify it in plugin's configuration in next release. Thank you.

**Comment by lalloni** [comment]
@shd101wyy that would be great!
