### ISSUE TITLE
插入 toc 预览中并不能实现跳转

### ISSUE THREAD

**Issue by luwantaoChina** [shd101wyy/vscode-markdown-preview-enhanced#237]
您好，我将这个插入 toc 后并不能跳转：
![20190607144750.png](https://csdn-blog-1258434200.cos.ap-shanghai.myqcloud.com/undefined20190607144750.png)

同样的文件，如果用 vscode 自带的预览，则是能够实现跳转的，望修复这个问题，非常感谢

**Comment by shd101wyy** [comment]
看截图你插入的这个 toc 不是用 mpe 插件 Create Toc 命令创建的，可能是问题原因

**Comment by luwantaoChina** [comment]
您好，应该不是这个原因。我之前开启了pandoc parser，现在关闭了这个就正常了
