### ISSUE TITLE
can't see line between box

### ISSUE THREAD

**Issue by hurrry** [shd101wyy/vscode-markdown-preview-enhanced#240]
![md](https://user-images.githubusercontent.com/22042546/59245888-19849300-8c4d-11e9-816c-1d8fa77f66a7.jpg)

**Comment by shd101wyy** [comment]
@hurrry  https://github.com/shd101wyy/markdown-preview-enhanced/issues/983

**Comment by hurrry** [comment]
thanks,it's ok now.
