### ISSUE TITLE
Plantuml version and license

### ISSUE THREAD

**Issue by gadams999** [shd101wyy/vscode-markdown-preview-enhanced#243]
Hi,

I noticed the included version of plantuml.jar is the March 2019 release. Recently the new v2 preprocessor has become generally available in the May or June releases.

When viewing the license version, I noticed that it is the default GPL version. Curious if that version conflicts with the NCSA license of the project overall? Plantuml does have other licenses that can be used such as MIT.

**Comment by shd101wyy** [comment]
It is embarrassing that I didn't pay attention to the license at all. I will include the MIT licensed plantuml in next release. 
You can also manually replace the plantuml.jar yourself, which is located at `~/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/plantuml`. If you are using vscode, then it starts with `~/.vscode/extensions/...`.

**Comment by shd101wyy** [comment]
I replaced the old one with the MIT licensed in the newest MPE release. Thank you!.

**Comment by parthi2929** [comment]
To be exact, `.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.6.2\node_modules\@shd101wyy\mume\dependencies\plantuml`.. I had to search :)
