### ISSUE TITLE
预览无法实时更新同步

### ISSUE THREAD

**Issue by suoyita** [shd101wyy/vscode-markdown-preview-enhanced#244]
系统版本：MacOS High Sierra
VSCode版本：1.35.1
MPE版本：0.4.1

当我使用Open Preview to the Side 时，修改源文件预览无法实时更新同步，但是使用Open Preview时是可以实时更新的。不知道是什么原因

**Comment by shd101wyy** [comment]
请问你插件中的 `markdown-preview-enhanced.scrollSync` 设置打开了吗?

**Comment by suoyita** [comment]
打开了的呀，而且不知道为什么快捷键也没法用了

**Comment by suoyita** [comment]
试验过后发现是因为没有保存成.md文件，抱歉
