### ISSUE TITLE
Using puppeteer to export PDF Failed！

### ISSUE THREAD

**Issue by Periter** [shd101wyy/vscode-markdown-preview-enhanced#248]
platform： Ubuntu 16.04+vscode 1.33.1+MPE0.4.2+nodejs v10.15.3
log：Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"

But when I used script likes 
```
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch();
  const page = await browser.newPage();
  await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle2'});
  await page.pdf({path: 'hn.pdf', format: 'A4'});

  await browser.close();
})();
```
it can create pdf.
Forthermore, after I used MPE to export html first then rewrite the path `await page.goto('https://news.ycombinator.com', {waitUntil: 'networkidle2'});` to `await page.goto('file:///home/tane/4T/code/Markdown/%E8%AE%BA%E6%96%87%E7%AC%94%E8%AE%B0/%E8%87%AA%E7%84%B6%E6%B5%81%E5%BD%A2%E7%9A%84%E5%88%A4%E5%88%AB%E5%99%A8.html'` it also works.
And I noticed that MPE can find the puppeteer path by itself from this guide manual.
![](https://i.loli.net/2019/06/25/5d119aeb61c0074456.png)

In my opinion, this problem should be MPE cannot find the path to run puppeteer, how can I modified the path manually, If the reason is not that, what can I do and hope for your reply.

**Comment by shd101wyy** [comment]
Hmm that is weird because puppeteer works fine on my Ubuntu 18.04.
Can you try install puppeteer globally first by running `npm install -g puppeteer` then uncheck the `usePuppeteerCore` option in MPE package settings? Thank you

**Comment by Periter** [comment]
> Hmm that is weird because puppeteer works fine on my Ubuntu 18.04 with `chromePath` to be empty and `usePuppeteerCore` checked.
> Can you try install puppeteer globally first by running `npm install -g puppeteer` then uncheck the `usePuppeteerCore` option in MPE package settings so the global puppeteer will be used? Thank you

Thx， it works. BYW，how can I change the PDF style likes page left margin.

**Comment by shd101wyy** [comment]
just write front-matter: https://shd101wyy.github.io/markdown-preview-enhanced/#/puppeteer?id=configure-puppeteer

please also refer to [puppeteer API](https://github.com/GoogleChrome/puppeteer/blob/v1.9.0/docs/api.md#pagepdfoptions).
So if you want to change left margin, you can write

```
---
puppeteer:
    margin:
        left: '5cm'
---
```

**Comment by Periter** [comment]
emm, thanks again.

**Comment by cherrot** [comment]
I have `chromium` instead of `google-chrome` installed on my Linux. Setting `chromePath` to `chromium` fixes this issue for me :)
