### ISSUE TITLE
Mermaid classDiagram breaks on any edit

### ISSUE THREAD

**Issue by kitsu** [shd101wyy/vscode-markdown-preview-enhanced#249]
There was an upstream bug I reported in knsv/mermaid#858 that appears to be fixed. It would be very helpful if you could update your  #dependency.

Thanks!

**Comment by shd101wyy** [comment]
Sure will do probably this weekend. Thank you!

**Comment by shd101wyy** [comment]
Sorry it seems like I won't have time to update it this week.

However, you can manually replace the `mermaid.min.js` and `mermaid.core.js` files yourself.  
If you are using atom, it is located at `~/.atom/packages/markdown-preview-enhanced/node_modules/@shd101wyy/mume/dependencies/mermaid/` directory.    
If you are using vscode, it is located at `/home/yiyiwang/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.4.2/node_modules/@shd101wyy/mume/dependencies/mermaid` directory.

Thank you

**Comment by kitsu** [comment]
Thanks, I was wondering if I could just patch it in.

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks.
