### ISSUE TITLE
导出html的几个问题想请教作者

### ISSUE THREAD

**Issue by Googolplex-C** [shd101wyy/vscode-markdown-preview-enhanced#250]
尊敬的作者，您好，我是一位大四电子系本科生，使用您的插件接近半年了，MPE 用于本地的 markdown 编辑真的非常顺手。
正因如此，我希望在写博客的时候，博客上呈现的效果能和我在本地使用 MPE 时的预览效果保持和接近一致，所以我选择直接使用 MPE 导出 html（当然如何将 html 直接部署到网络上又是另一个问题了），在使用导出功能的时候我产生了几个疑问：
1、如果 markdown 源文件中具有 svg、png等资源文件，那么这个 html 是不是无论在任何时候都要于这些资源文件放在同一目录下？
2、如果 markdown 源文件中含有 mathjax、graphviz、mermaid 等需要渲染的内容，那么导出的单独一个 html 是如何使得这些元素能够成功被渲染的？
3、如果我需要把 html 放置在网络上（比如直接上传至 github pages 然后以静态网页方式访问），那么导出的时候是不是一定要选择 “cdn hosted” 选项？
4、导出 html 时，offline 和 cdn hosted 选项有什么不一样吗？
5、为什么，导出 html 只会产生一个单独的 html 文件？CSS 文件呢？（我改过 style.less 使得图片居中）
鉴于我的计算机水平不太好（尤其是对这些前端相关的知识了解甚少），我曾在网上搜索也没有获取太多我能看懂的信息，因此迫切渴望得到您的帮助和解答，如果您不吝赐教，这将给我莫大的帮助！ @shd101wyy

**Comment by shd101wyy** [comment]
同学你好，

> 1、如果 markdown 源文件中具有 svg、png等资源文件，那么这个 html 是不是无论在任何时候都要于这些资源文件放在同一目录下？

是的是这样的。  
另一种做法是 front-matter 中还有一个选项叫做 `embed_local_images`，如果设为 `true` 则可以将本地的 svg 和 png 以 base64 的格式直接写到 html 中，当然这样会使的 html 的体积便大。

```
---
html:
  embed_local_images: true
---
```

> 2、如果 markdown 源文件中含有 mathjax、graphviz、mermaid 等需要渲染的内容，那么导出的单独一个 html 是如何使得这些元素能够成功被渲染的？

这个如果你要把 html 放到你的服务器上的话，导出时候需要选用 `cdn hosted`，这样这个 html 文件就会获取 jsdeliver 此类 cdn 服务器上的 js 文件 和 css 文件（例如获取 mathjax.js 来渲染数学符号）。

> 3、如果我需要把 html 放置在网络上（比如直接上传至 github pages 然后以静态网页方式访问），那么导出的时候是不是一定要选择 “cdn hosted” 选项？  

是的

> 4、导出 html 时，offline 和 cdn hosted 选项有什么不一样吗？  

如果你有意放导出的 html 到你的服务器上（远程而不是本地），那么就要选择 `cdn hosted`。例如 mathjax 的话需要依赖 `mathjax.js` 文件，`cdn hosted` 导出的 html 会读取 jsdeliver 这个 cdn 服务器上的 mathjax.js 文件，而 `offline` 导出的文件就只会读取你本地机子上的 mathjax.js 文件。所以 `offline` 导出的 html 文件放到服务器上会发现读取不到本应该是在你本地机子上的 mathjax.js 文件。

> 5、为什么，导出 html 只会产生一个单独的 html 文件？CSS 文件呢？
因为导出的时候 `css` 文件已经被以 `<style>...</style>` 的形式写到 html 中了，不需要再从外部链接 css 文件。


谢谢～

**Comment by Googolplex-C** [comment]
天啊，这么快收到您的回复，真是受宠若惊！！好像还是第一次有这样的大神以这么快的速度详细地回复我的疑问，您的解答真的非常详细易懂，一下子理清了我脑子里的一团乱麻，再次向您表示感谢！祝您生活愉快！
