### ISSUE TITLE
rendering with plantuml server

### ISSUE THREAD

**Issue by kmasuyama** [shd101wyy/vscode-markdown-preview-enhanced#255]
Would it be possible to use a separate plantuml server for rendering instead of the builtin .jar? I can think of a few reasons this may be beneficial:

1. consistency. If the plantuml rendering changes across versions, using the same server would eliminate inconsistency between different environments in multi-user settings.
1. installation privilege. Some users may not be allowed to install dependencies (java, graphviz) on their computers, but are provided with a separate plantuml server.

**Comment by jesshaw** [comment]
+1

**Comment by shd101wyy** [comment]
Sorry for the super delay. This feature is now supported in the latest version of mpe. You could now modify the `plantumlServer` in the extension settings. (Restarting the editor might be required for the setting to take effect). 
Thank you and credit to @logwolvy :)
