### ISSUE TITLE
override theme for markdown preview and not slides

### ISSUE THREAD

**Issue by andaag** [shd101wyy/vscode-markdown-preview-enhanced#26]
Hi

I want a setup with a dark theme that matches a vscode dark theme. The way I've done this is modify style.less to add background: none;. This works fine with github dark + monokai for example, and looks very nice. However, it breaks the slides example horribly.

Is there any way to override this style only in markdown mode and not in presentation mode. Or can I solve this in some other way?

**Comment by shd101wyy** [comment]
Hi, under previewTheme there should be a none.css option.

**Comment by andaag** [comment]
That is true, I used that one with the monokai theme and it did not look right, but that might have been more of a problem with the monokai theme than with the functionality in the plugin!

Thank you!
