### ISSUE TITLE
rendering is unreadable when MD contains $

### ISSUE THREAD

**Issue by Josverl** [shd101wyy/vscode-markdown-preview-enhanced#262]
tried the extension briefly and will be installing in favor of a more basic, but effective other one, as it as it does not render quite simple markdown properly 

if the md contains something like 
```
### -EnableSdnProviderForBroadcastMeeting
If set to $true, broadcast meeting streams are enabled to take advantage of the network and bandwidth management capabilities of your Software Defined Network (SDN) provider.
The default is $false.
```
the rendering after a `$` becomes nearly unreadable. The opposite of what I would expect.

see below screenshot 

![image](https://user-images.githubusercontent.com/981654/63081486-012e3e80-bf44-11e9-8456-98e55c40edf1.png)

**Comment by shd101wyy** [comment]
Content within `$...$` were rendered as math expression. You can escape `$` by adding `\` ahead like `\$`

**Comment by Josverl** [comment]
No,

  1.  I have no interest of changing the vast majority the documents on github and in the repro’s i work in to support your extension .
  2.  That would make that content rendered incorrectly in all the reference inmplementations.

your logic does not hold up ,
its supposed to be a tool that saves work , not increase it
Your default rendering should work with the standards.

**Comment by shd101wyy** [comment]
Then you can turn off the `Mather Rendering` from the extension settings.

**Comment by Josverl** [comment]
Did the simpler thig : Uninstalled 😉

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by shd101wyy** [comment]
😎
