### ISSUE TITLE
command 'markdown-preview-enhanced.openPreviewToTheSide' not found

### ISSUE THREAD

**Issue by aaubry** [shd101wyy/vscode-markdown-preview-enhanced#274]
This extension was working the last time I used it, but not anymore. In the meantime, I probably installed a update to VSCode, but I don't know which version I had before.
I tried uninstalling the extension, deleting both `~/.mume` and `~/shd101wyy.markdown-preview-enhanced-0.4.3` but that did not help. Is there anything else that I can try ?

VSCode version:
```
Version: 1.38.1 (user setup)
Commit: b37e54c98e1a74ba89e03073e5a3761284e3ffb0
Date: 2019-09-11T13:35:15.005Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Extension version:
```
Name: Markdown Preview Enhanced
Id: shd101wyy.markdown-preview-enhanced
Description: Markdown Preview Enhanced ported to vscode
Version: 0.4.3
Publisher: Yiyi Wang
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=shd101wyy.markdown-preview-enhanced
```

**Comment by shd101wyy** [comment]
Hi there. Sorry for the trouble. I have been very busy recently on my job. I will take a look at the issue next week when I have a break. Thanks.

**Comment by aaubry** [comment]
No worries. I don't want to put pressure on you. Thanks!

**Comment by Zoranner** [comment]
> Hi there. Sorry for the trouble. I have been very busy recently on my job. I will take a look at the issue next week when I have a break. Thanks.

你好，我也遇到了这个问题，希望可以帮忙解决。👀

**Comment by khose-ie** [comment]
老哥最近空了没，我也碰到这个问题了。

**Comment by shd101wyy** [comment]
@khose-ie 我刚才又发了一个版本 `0.5.8`，应该是修复了，你试试？多谢

**Comment by khose-ie** [comment]
我刚刚直接在github上下了一个手动导入了，是可以的，可能是商店里的有问题？

**Comment by shd101wyy** [comment]
@khose-ie 你是什么操作系统？vscode 版本是什么呢？

**Comment by khose-ie** [comment]
我又重新从商店下了试试，好用了老哥，辛苦了，最开始是windows和mac上都不行，现在可以了。

**Comment by shd101wyy** [comment]
@khose-ie 赞 👍

**Comment by khose-ie** [comment]
@shd101wyy 是不支持mermaid？还是我没配置对嘛？为啥我的mermaid图是黑的？

**Comment by shd101wyy** [comment]
@khose-ie 去插件设置里更改一下 `mermaidTheme` 就好了

**Comment by khose-ie** [comment]
@shd101wyy 哇可以了，感谢老哥，非常好用！！！

**Comment by askarthikkumar** [comment]
I am having the same issue. Sometimes it opens and sometimes it gives this error.

**Comment by shd101wyy** [comment]
@askarthikkumar Seems like it is related with the vscode webview issue:

https://github.com/microsoft/vscode/issues/89038

I haven't found a solution yet :(

**Comment by navjotjsingh** [comment]
Same issue with VS Code 1.46.1 on Ubuntu 20.04.

`Version: 1.46.1
Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
Date: 2020-06-17T21:13:08.304Z
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 5.4.0-37-generic`

**Comment by rexebin** [comment]
> Same issue with VS Code 1.46.1 on Ubuntu 20.04.
> 
> ```
> Commit: cd9ea6488829f560dc949a8b2fb789f3cdc05f5d
> Date: 2020-06-17T21:13:08.304Z
> Electron: 7.3.1
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Linux x64 5.4.0-37-generic
> ```

I uninstalled the extension, then reinstalled it without restarting vs code first, problem persist.  However, if I uninstall the extension, then restart vs code and install again, the problem is fixed. Hope it helps.

**Comment by HarmonyCode7** [comment]
rexebin I had the same issue too, your solution seems to fix it. Thank you

**Comment by nguxx** [comment]
same issue

**Comment by nht270** [comment]
same issue in VS Code 1.82.2 on Windows 10

**Comment by shd101wyy** [comment]
Usually restarting the vscode will help.

**Comment by cuixing158** [comment]
I updated vscode to the latest version and it worked.

**Comment by marhyno** [comment]
> I updated vscode to the latest version and it worked.

this resolved it - 1.83.1 now works

**Comment by TwithZ** [comment]
> > I updated vscode to the latest version and it worked.
> 
> this resolved it - in VS code version 1.83.1 it now works

I also met this question, I installed a previous version of the plugin, and it works now. It seem them the latest version this plugin is something wrong.

**Comment by zhubinqiang-intel** [comment]
I have faced this issue on the v0.8.4. I rolled back to v0.6.10 and it worked well.

**Comment by shd101wyy** [comment]
The latest version of this extension only works for vscode 1.82.0 and above. you will need to update your vscode otherwise it will not work.

**Comment by TwithZ** [comment]
> The latest version of this extension only works for vscode 1.82.0 and above. you will need to update your vscode otherwise it will not work.

Thank you my friend, I already tried this method, it works!!! So I think the latest plugin must match to latest VSCode!

**Comment by shd101wyy** [comment]
The latest version of this extension requires VSCode 1.70.0 and above
