### ISSUE TITLE
Error: Unable to open 'MPE Preview': Cannot read property 'tex2jax' of null.

### ISSUE THREAD

**Issue by ATaiM** [shd101wyy/vscode-markdown-preview-enhanced#28]
When trying to open the preview (both with `Ctrl+Shift+M` and `Ctrl+Shift+P > 'Markdown Preview Enhanced: Open Preview'`, the following error message appears.

![image](https://user-images.githubusercontent.com/21041668/28260562-e01dda3e-6adb-11e7-809f-f8c33afba244.png)

I installed MPE on VSCode just yesterday and it worked until I shut down my computer normally and tried to work in markdown this morning.

MPE works flawlessly with KaTeX. This problem only occurs when rendering math with MathJax.

I don't know if it is related, but MPE stopped working on Atom as well, where the preview just won't open without any error message. This problem also just occurred this morning. I submitted an issue on this in the repository for MPE on Atom: https://github.com/shd101wyy/markdown-preview-enhanced/issues/504

Any help would be much appreciated.

**Comment by shd101wyy** [comment]
Try remove the folder "~/.mume" then restart editor? ($HOME_DIRECTORY/.mume)

**Comment by ATaiM** [comment]
That fixed the issue for me!
Thanks a lot for the quick response!

**Comment by jailsonfm** [comment]
How can I remove the folder "~/.mume"?
I didn't find it yet. I have the same problem. The preview window opens but doesn't show anything.
Thanks
J

**Comment by ATaiM** [comment]
For me it was in 

```C:\Users\```

I use Windows 10.

**Comment by shd101wyy** [comment]
Since a lot of people are getting this issue, the I think it's a bug. I will have a look next weekend.
