### ISSUE TITLE
Dark theme not supported

### ISSUE THREAD

**Issue by yunti** [shd101wyy/vscode-markdown-preview-enhanced#286]
From an earlier issue it appears that support for a dark theme was added to the preview #256 . However currently when using the preview with a dark them (atom's pro dark theme) the preview appears light with a light background.  The default vscode preview appears with a dark preview as expected.

**Comment by shd101wyy** [comment]
You can change the preview theme from the extension settings. Search for `markdown-preview-enhanced:previewTheme` then change the preview theme to the one you want.
