### ISSUE TITLE
[Bug] Resize images

### ISSUE THREAD

**Issue by Supportic** [shd101wyy/vscode-markdown-preview-enhanced#31]
Problem:
If you try to import a picture and give it width + height, only the width is scaling properly.
This problem only occurs when you try to convert from .md to .pdf.

How to recreate the problem:
- create a .md file
- try to import a picture and set the resolution (height needs to be higher):
"@import "test.jpg" {width:"400px", height:"1000px", title:"my title", alt:"my alt"}

OS: Win10
IDE: vscode
Converter from .md to .pdf: phantomJS

**Comment by Digital-Playground** [comment]
Nevermind this issue does not occur in the preview, only in the result.

**Comment by shd101wyy** [comment]
@Digital-Playground yes you are right. I will try to fix it next weekend.
