### ISSUE TITLE
mermaid : vscode preview not breaking on <br/> tag in Notes

### ISSUE THREAD

**Issue by mameen** [shd101wyy/vscode-markdown-preview-enhanced#313]
In mermaid format, adding a `<br/>` inserts line breaks in notes.. This doesn't work in the preview window in vscode, but works well in the browser..

```mermaid
sequenceDiagram

A ->> B : hi
Note right of A: this is a<br/>multi<br/>line<br/>note !
```
## in vscode preview:
![image](https://user-images.githubusercontent.com/3342359/72407058-32898100-3713-11ea-8c84-f71af7389250.png)

## On mermaid, and browser:
![](https://mermaid.ink/img/eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5cbkEgLT4-IEIgOiBoaVxuTm90ZSByaWdodCBvZiBBOiB0aGlzIGlzIGE8YnIvPm11bHRpPGJyLz5saW5lPGJyLz5ub3RlICFcbiIsIm1lcm1haWQiOnsidGhlbWUiOiJkZWZhdWx0In19)

**Comment by kingreatwill** [comment]
mermaid 能升级到8.4.5吗

**Comment by mameen** [comment]
I didn't investigate it in depth.. the generated HTML looks OK.. in fact when opened in browser it is fine.. I could try it locally.. is it the one from https://unpkg.com/mermaid@8.4.5/dist/mermaid.min.js ?

**Comment by mameen** [comment]
OK I replaced the one in `\.vscode\extensions\shd101wyy.markdown-preview-enhanced-0.5.1\node_modules\@shd101wyy\mume\dependencies\mermaid`  and the issue is the same.. Note not broken in preview, but works fine in browser

**Comment by kingreatwill** [comment]
Thanks!

**Comment by mameen** [comment]
OK, here is what is going on.. while the arrows are getting escaped in the html input to mermaid, the html tags inside the notes are not.. here is my workaround :

```js
  onDidParseMarkdown: function(html) {
    return new Promise((resolve, reject)=> {
      html = html.replace(/<br>/gm, "&lt;br&gt;");
      return resolve(html)
    })
```

This makes the output look correct..

**Comment by mameen** [comment]
OK, you can close the issue.. replacing `<br>` with `&lt;br&gt;` solved it for me..
```mermaid
sequenceDiagram

A ->> B : hi
Note right of A: this is a&lt;br&gt; multiline &lt;br&gt;note 
```
