### ISSUE TITLE
上传sm.ms失效，一直卡在 Uploading

### ISSUE THREAD

**Issue by oOtroyOo** [shd101wyy/vscode-markdown-preview-enhanced#314]
![批注 2020-01-21 175704](https://user-images.githubusercontent.com/19978148/72794777-7fbba480-3c77-11ea-986a-31104891cf5c.jpg)

好像就一直卡在 Uploading ，使用 imgur是可以的，但是这个我不常用毕竟要翻墙。

**Comment by shd101wyy** [comment]
这个好像是因为 sm.ms api 更新了的缘故。我这几天在医院，得春节期间有空了再看看了。谢谢

**Comment by shd101wyy** [comment]
应该是修复了，谢谢，新年快乐
