### ISSUE TITLE
本地图片无法预览

### ISSUE THREAD

**Issue by Icecream-blue-sky** [shd101wyy/vscode-markdown-preview-enhanced#321]
版本：
vscode以及vscode-markdown-preview-enhanced插件都是最新版本。
问题：
使用相对路径和绝对路径都无法预览图片，只有当图片与md文件处于相同目录时，使用相对路径才显示图片。
![test](https://user-images.githubusercontent.com/26771037/74831372-14d1bc00-5350-11ea-9457-2f9ede97c3fc.png)
md文件保存在1文件夹下，图片保存在2文件夹下，1文件夹下还有个images子文件夹。
![image](https://user-images.githubusercontent.com/26771037/74831498-4ba7d200-5350-11ea-9896-aa48f53188d5.png)
我同学的好像使用的是老版本vscode(大概去年12月份），它的上面相同情况都显示正常，实在不知道哪里出了问题，期待大佬答复！

**Comment by lyuangg** [comment]
绝对路径的图片不显示。

vscode 版本: 1.45.1
插件版本：0.5.3
系统：macOS 10.15.4

**Comment by Icecream-blue-sky** [comment]
问题已解决，不是插件的问题，而是需要在资源管理器(ctrl+shift+e)中打开图片和博客所在的文件夹，而后vscode才能识别路径。[https://github.com/microsoft/vscode/issues/99588](url)
