### ISSUE TITLE
Move ~/.mume directory according to XDG Base Directory specification

### ISSUE THREAD

**Issue by retnikt** [shd101wyy/vscode-markdown-preview-enhanced#346]
Please consider moving it to an appropriate place according to the XDG Base Directory spec. Here is a good article on it: https://wiki.archlinux.org/index.php/XDG_Base_Directory, including a list of applications which use it, including VSCode, Git, LibreOffice, KDE, VLC, systemd...

The specification is here https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html. This will reduce the amount of clutter in the user's home directory.

It would also need to be moved for the Atom version I suppose, if the intent is to provide compatibility between them

**Comment by shd101wyy** [comment]
Hi @retnikt , you can now configure the `configPath` in the vscode version. Thank you.
