### ISSUE TITLE
imported pdf preview issue

### ISSUE THREAD

**Issue by askarthikkumar** [shd101wyy/vscode-markdown-preview-enhanced#362]
I cannot preview any images or pdfs which have been added by the ```@import``` statement. I just get image not found icons.
I checked the console log in the developer tools and found this error message
```
Error: Unable to read file '<global path>/DocName.png?0.8128168111460599' (EntryNotFound (FileSystemError): Error: ENOENT: no such file or directory, open '<global path>/DocName.png?0.8128168111460599')
    at e.doReadAsFileStream (fileService.ts:457)
```

It is appending some weird string of numbers to the end of the path name. Please let me know how to fix this.

Update: Rolling back to version 0.5.3 solved it. So maybe there is some issue with the latest version.

**Comment by shd101wyy** [comment]
Thank you for reporting the issue. I will take a look soon.

**Comment by shd101wyy** [comment]
Alright seems like the whole `@import` is broken. I will fix it after this [PR](https://github.com/shd101wyy/mume/pull/181) gets merged. Thank you.

**Comment by askarthikkumar** [comment]
Hi, 
Also wanted to add that the same issue affects rendering latex code chunks in the latest version too.

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks.

**Comment by askarthikkumar** [comment]
Import statement works. Thank you.
