### ISSUE TITLE
Preview gives a blank screen

### ISSUE THREAD

**Issue by glebovitz** [shd101wyy/vscode-markdown-preview-enhanced#367]
activating markdown preview enhanced from VS Code gives a blank screen (black)

what I did:
created a markdown file that renders correctly in github.
selected Open Markdown Preview enhanced from the command list.

what I expected:
see my markdown rendered in a new edit tab

actual results:
new tab opened, but background was black and no text was rendered.

System:
OSX 10.14.6 (18G5033) 
VSCode:
Version 1.30.2 (1.30.2)

**Comment by aes421** [comment]
I am having the same problem.

System:
Windows 10
VSCode 1.33.1

**Comment by gabyx** [comment]
Sometimes when you reopen vscode it works again, also try closing all tabs first, an reinstall 

Update your VS Code -> to 1.46

**Comment by gabyx** [comment]
Reopen if it persists...

**Comment by aes421** [comment]
Updating visual studio code worked.  Thanks!

**Comment by natea** [comment]
I'm seeing a blank screen when trying to preview a markdown file. Do i need to have some system level dependencies installed in order for the extension to work?
