### ISSUE TITLE
auto unfold <detail> when editing

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [shd101wyy/vscode-markdown-preview-enhanced#371]
Issue Type: <b>Feature Request</b>

![image](https://user-images.githubusercontent.com/57612792/83935477-7e38e600-a7ec-11ea-8bbf-6bf1429fced6.png)

I hope when I am editing the detail it can be unfolded, so I can easily see the changes.

Extension version: 0.5.10
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:22.494Z)
OS version: Linux x64 5.4.0-33-generic

**Comment by kis9a** [comment]
I use open attribute when editing.
```
<details open>
```
I think auto unfold implement is complex.
