### ISSUE TITLE
不显示图片

### ISSUE THREAD

**Issue by zchrissirhcz** [shd101wyy/vscode-markdown-preview-enhanced#386]
Hi,

我的环境：
```
Version: 1.46.0-insider (system setup)
Commit: cd41dd1f6065db76c77c6e2f659bb50e6f558dec
Date: 2020-05-29T05:51:32.662Z
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
```

vscode-markdown-preview-enhanced插件，最新版，手动安装的.vsix（vscode插件里搜索下载，一直显示installing，没有安装成功）。

插入图片使用的是：

```
![avatar](pedestrian.png)
```
其中图片是当前目录图片；VSCode自带的markdown预览可以显示图片，而markdown-preview-enhanced则显示不出图片：

![image](https://user-images.githubusercontent.com/3831847/86887527-42ff3f00-c12b-11ea-9e66-368b3e69f95d.png)

**Comment by liuyatao** [comment]
Win10确实是这样的，不知道什么原因，但是macOS上又是好的，希望能解决一下，本地图片不能加载出来确实有点不友好了，这是基础功能啊
