### ISSUE TITLE
Katex \tag is overlapped when a formula is too long or viewed with split windows

### ISSUE THREAD

**Issue by langtutheky** [shd101wyy/vscode-markdown-preview-enhanced#389]
## Description

Adding a \tag to a formula, the \tag would overlap the formula when rendered if the formula is too long

## To reproduce

1. Type a very long formula
2. Insert a \tag at the end of the formula
3. See the error on the preview window

## Expected behaviors

No matter how long the formula is, the \tag should always be at the tail of the formula and not overlapping it

## Environments

 - Markdown Preview Enhanced Version: 0.5.12
 - Visual Studio Code Version: 1.47.2
 - Device: Desktop
 - OS: MacOS Catalina 
 - OS Version: 10.15.5
 - Browser: Google Chrome
 - Broswer Version: 83.0.4103.116

## Screenshots

- Short formula renders as expected on VSCode and Chrome

```Tex
\[\forall v \forall w \forall x \forall y \forall z [[Bar(z) \wedge Foo(y) \wedge [\neg Baz(y)] \wedge Bar(x, y) \wedge Foo(w, y, z) \wedge Bar(v, w)] \rightarrow v = x] \tag{99} \]
```

<img width="1390" alt="Screen Shot 2020-07-16 at 10 41 36 PM" src="https://user-images.githubusercontent.com/9475206/87809215-e200f680-c80f-11ea-88b3-d5d6a14a5901.png">

<img width="1440" alt="Screen Shot 2020-07-16 at 10 48 42 PM" src="https://user-images.githubusercontent.com/9475206/87812594-4bcfcf00-c815-11ea-8d15-63833999f9ec.png">

- Long formula renders incorrectly on VSCode and Chrome

```Tex
\[\forall v \forall w \forall x \forall y \forall z [[Bar(z) \wedge Foo(y) \wedge [\neg Baz(y)] \wedge Bar(x, y) \wedge Foo(w, y, z) \wedge Bar(v, w)] \rightarrow v = x] \forall v \forall w \forall x \forall y \forall z [[Bar(z) \wedge Foo(y) \wedge [\neg Baz(y)] \wedge Bar(x, y) \wedge Foo(w, y, z) \wedge Bar(v, w)] \rightarrow v = x] \tag{99} \]
```

<img width="1374" alt="Screen Shot 2020-07-17 at 10 02 29 AM" src="https://user-images.githubusercontent.com/9475206/87812315-cfd58700-c814-11ea-8b52-a7da821f7944.png">

<img width="1440" alt="Screen Shot 2020-07-16 at 10 48 58 PM" src="https://user-images.githubusercontent.com/9475206/87812558-39559580-c815-11ea-853d-bd217362ae03.png">

## Note

I am aware that this could be a problem of the underlying Katex engine that this package is using but I don't have the appropriate context to file an issue with them

**Comment by rmoraisr** [comment]
The problem is with the Katex engine. You can check this at [Katex website](https://katex.org)

![image](https://user-images.githubusercontent.com/57760310/87814630-76804e80-c83a-11ea-966c-262424f07f1b.png)

[MathJax](https://www.mathjax.org/#demo) is rendering it just fine

**Comment by langtutheky** [comment]
@rmoraisr Noted, I will file the issue with Katex using the check you have shown.
