### ISSUE TITLE
在预览中点击本地文件链接, 被系统拦截

### ISSUE THREAD

**Issue by databinQ** [shd101wyy/vscode-markdown-preview-enhanced#391]
链接是本地另外一个md文件, 点击后显示**需要使用新应用以打开此vscode-webview-resource**链接.
请问这种情况是vscode本身的原因, 还是插件某处可以设置? 

更新了vscode之后才出现的这种情况, 看过了插件的所有设置项, 也大致搜索了下, 没有发现解决方法.

**Comment by spectereye** [comment]
met the same issue ...

**Comment by spectereye** [comment]
more info.: 
if i try link below in vscode builtin markdown preview, no problem to open the file,
but in MPE preview, it popup "need a new app to open this vscode-webview-resource link",
so it seems to be MPE's issue

``[foo](./assets/foo.txt)``

**Comment by shd101wyy** [comment]
我也发现了这个问题，我找个时间修复一下

I also found the issue. I will fix it soon.

**Comment by shd101wyy** [comment]
应该是在最新版本中修复了

Should be fixed now in the newest patch

**Comment by shimushi2172** [comment]
In version v0.6.2  when link to local markdown file by [](README.md)  indicates cannot open
https://file+.vscode-resource.vscode-cdn.net/c:/N-5CD7449W4T-Data/f1shi/Documents/products/easytooptimization/README.md
