### ISSUE TITLE
Paragraphs are rendered across multiple lines instead of a single line

### ISSUE THREAD

**Issue by adamalston** [shd101wyy/vscode-markdown-preview-enhanced#398]
The Markdown [documentation](https://daringfireball.net/projects/markdown/syntax#p) says that paragraphs should require two newlines instead of one to form a new paragraph:

> A paragraph is simply one or more consecutive lines of text, separated by one or more blank lines. (A blank line is any line that looks like a blank line — a line containing nothing but spaces or tabs is considered blank.) Normal paragraphs should not be indented with spaces or tabs.

I have set up a few test badges to demonstrate:
```markdown
<!-- Markdown -->
![Test0](https://img.shields.io/badge/%E2%98%84%EF%B8%8F-test0-orange)
![Test1](https://img.shields.io/badge/%F0%9F%9B%B0%EF%B8%8F-test1-brightgreen)
![Test2](https://img.shields.io/badge/%E2%98%80%EF%B8%8F-test2-yellow)
```

The extension renders these badges on three different lines:

![Test0](https://img.shields.io/badge/%E2%98%84%EF%B8%8F-test0-orange)
![Test1](https://img.shields.io/badge/%F0%9F%9B%B0%EF%B8%8F-test1-brightgreen)
![Test2](https://img.shields.io/badge/%E2%98%80%EF%B8%8F-test2-yellow)

However, these badges should be rendered on one line because there is a single newline separating the entries with no blank lines separating them:

![Test0](https://img.shields.io/badge/%E2%98%84%EF%B8%8F-test0-orange) ![Test1](https://img.shields.io/badge/%F0%9F%9B%B0%EF%B8%8F-test1-brightgreen) ![Test2](https://img.shields.io/badge/%E2%98%80%EF%B8%8F-test2-yellow)

---

Considering that Markdown is converted into HTML, I tried to replicate the issue using `img` tags:
```html
<!-- HTML -->
<img src="https://img.shields.io/badge/%E2%98%84%EF%B8%8F-test0-orange"/>
<img src="https://img.shields.io/badge/%F0%9F%9B%B0%EF%B8%8F-test1-brightgreen"/>
<img src="https://img.shields.io/badge/%E2%98%80%EF%B8%8F-test2-yellow"/>
```

The extension correctly renders these elements all on a single line:

<img src="https://img.shields.io/badge/%E2%98%84%EF%B8%8F-test0-orange"/> <img src="https://img.shields.io/badge/%F0%9F%9B%B0%EF%B8%8F-test1-brightgreen"/> <img src="https://img.shields.io/badge/%E2%98%80%EF%B8%8F-test2-yellow"/>

**Comment by rmoraisr** [comment]
MPE uses [Markdown-ti](https://github.com/markdown-it/markdown-it) to render.
Markdown-it that follows [CommonMark Spec](https://spec.commonmark.org) and has enhanced features, so it is a better place to check for a complete syntax.

This said, as you can see at MPE documentation, Markdown Preview Enhanced is a SUPER POWERFUL markdown extension for Atom and Visual Studio Code, so this has extra features to make you life easier.

You can check under MPE extension settings the option to Break (or not) on single line.


<img width="829" alt="image" src="https://user-images.githubusercontent.com/57760310/88805878-1799ce00-d186-11ea-813e-7744335b6ddb.png">VSCode extension settings



*I am not a native English speaker so, I apologize in advance if I was rude. Please correct me always that you get a chance, you'll be making me a huge favor*

**Comment by adamalston** [comment]
I changed that setting and a few others and now it works as intended. Thanks for the suggestion.
