### ISSUE TITLE
plain text turns into emoji

### ISSUE THREAD

**Issue by zcysxy** [shd101wyy/vscode-markdown-preview-enhanced#399]
When I type `:)` as plain text, it shows as an emoji 😀 in the preview. Is it a bug or a feature? And how can I turn it back to plain text?

**Comment by adamalston** [comment]
I'm am pretty sure the conversion is a feature. However, there is a workaround.

You can insert a [zero-width space](https://en.wikipedia.org/wiki/Zero-width_space#Usage) before `:)` and it will maintain composition without being converted. 

Zero-width space: `&#8203;` or `&ZeroWidthSpace;`
