### ISSUE TITLE
Some diagrams not rendering correctly because of bug in Mermaid library

### ISSUE THREAD

**Issue by DawMatt** [shd101wyy/vscode-markdown-preview-enhanced#402]
A [mermaid bug](https://github.com/mermaid-js/mermaid/issues/1480#issuecomment-656052057) is causing certain diagrams to render incorrectly in the plugin. An example of a diagram rendered by Markdown Preview Enhanced is included below:

![https://user-images.githubusercontent.com/476705/84981737-88f26400-b178-11ea-9914-9c2f2fb0436e.png](https://user-images.githubusercontent.com/476705/84981737-88f26400-b178-11ea-9914-9c2f2fb0436e.png)

Could the plugin please be updated to use a current version of the Mermaid library, which resolves this issue?

**Comment by shd101wyy** [comment]
If you can't wait you could manually replace the mermaid.min.js file located at `~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.5.13/node_modules/@shd101wyy/mume/dependencies/mermaid/` directory.  
I will issue a new release when I have time. Thank you

**Comment by DawMatt** [comment]
@shd101wyy , thanks for sharing the suggestion. I did try to replace those dependencies myself but couldn't get this to work.

I first tried replacing just mermaid.min.js, then mermaid.core.js as well, but the preview would just show the text in the mermaid code fences and there was a spinning circle on the preview page. When I restored the older versions of those files the preview did work again though obviously with the same limitations as the older diagramming versions.

I shutdown VS Code before each time I replaced the files so I could make sure there weren't any file locking/caching issues impacting the success of the upgrade.

Any suggestions on what else I might try to allow manually upgrading the mermaid version?

**Comment by DawMatt** [comment]
@shd101wyy , can you please advise whether there are any other instructions on how to manually update a dependency within the plugin? I tried to follow the advice you supplied last month but I couldn't get it to work.

**Comment by DawMatt** [comment]
Thanks, I can confirm this bug has been resolved in v0.5.16 of the plugin, though it may have already been addressed in v0.5.15.

It would still be useful if updated instructions could be provided for manually updating dependencies such as this.
