### ISSUE TITLE
feature request: Allow spaces in [[wiki links]]

### ISSUE THREAD

**Issue by cedardocster** [shd101wyy/vscode-markdown-preview-enhanced#430]
I have thousands of notes like "errands list.md" that have spaces in the filenames.  Finding your extension made my personal notes so much more usable.  I haven't been able to find any Visual Studio Code Markdown enhancements that allow wiki links to have spaces in them.  Your extension seems quite advanced, so I was hoping it would be a trivial thing to add this functionality.

Thanks,
 
- Dave

**Comment by Will-At-Carrier-Pigeon** [comment]
There is a workaround that doesnt force you to change the filename.

Using wikilinks;
```md
[[my&#32;file.md]]
```
 Using references;
```md
[go to my file][my file]
...
[my file]: ./my&#32;file.md
```
Using links;
```md
[go to my file][./my&#32;file.md]
```

`&#32;` is the escape for the space character, meaning you wont get any weird symbols in the link text.

Hope this helps.

**Comment by bmrussell** [comment]
> I have thousands of notes like "errands list.md" that have spaces in the filenames. Finding your extension made my personal notes so much more usable. I haven't been able to find any Visual Studio Code Markdown enhancements that allow wiki links to have spaces in them. Your extension seems quite advanced, so I was hoping it would be a trivial thing to add this functionality.
> 
> Thanks,
> 
>     * Dave

I'd be keen to see this too, as when taking notes with an extension like Foam, having all your wiki links break is annoying. Thanks for the workaround Willster but if spaces were allowed it would be a lot less cumbersome.

**Comment by WillsterJohnson** [comment]
If the place your markdown is going to be parsed into web content can support spaces in Wkiklinks, I'd recommend just using [Obsidian](https://obsidian.md/).
It doesn't have all the magic which VSCode gives, but it's a solid markdown editor.

Plus because it's for-profit (they have a cloud publishing thing - the app is completely free) they're able to invest a lot more into it than open source projects. It's better, but it's closed source.

**Comment by bmrussell** [comment]
> If the place your markdown is going to be parsed into web content can support spaces in Wkiklinks, I'd recommend just using [Obsidian](https://obsidian.md/). It doesn't have all the magic which VSCode gives, but it's a solid markdown editor.
> 
> Plus because it's for-profit (they have a cloud publishing thing - the app is completely free) they're able to invest a lot more into it than open source projects. It's better, but it's closed source.

Yeah I'm a big fan of Obsidian. Harder to use in a corporate environment though.

**Comment by shd101wyy** [comment]
Spaces in wiki link is now supported. I will also add backlinks to the MPE.
