### ISSUE TITLE
HTML/CSS color setting does not work by  PDF printing in the version 0.5.14

### ISSUE THREAD

**Issue by aidibi** [shd101wyy/vscode-markdown-preview-enhanced#448]
Hi Wang,

There is an issue which I think is a bug in the new version and I hope you can help to solve it.
The issue is color setting in HTML or CSS does not work after printing it to PDF file by the path 「Chrome(PUPPETER)->PDF」.(preview and HTML printing works fine)
As my searching it did work in the pre-version so I guess this is a bug.
Here I attached the sample code, "bordercolor="#333333"" works in the preview but not PDF file.
Even you set the color in CSS it still does not work.

Thanks for your help in advance.
Xin

`<table border="2"  cellspacing="0" cellpadding="2" bordercolor="#333333">`
`<tr>`
`<td bgcolor="#90ee90" width="200"><font>取得項目</font></td>`
`<td bgcolor="#FFFFFF" colspan="4" width="600"><font>会社コード	T001	</font></td>`
`</tr>`
`</table>`

**Comment by aidibi** [comment]
Hi, Can anybody help to check the issue?

**Comment by shd101wyy** [comment]
@aidibi You could go to the extension settings then set

```
    "markdown-preview-enhanced.printBackground": true,
```

**Comment by aidibi** [comment]
> @aidibi You could go to the extension settings then set
> 
> ```
>     "markdown-preview-enhanced.printBackground": true,
> ```

That solved my issue, thanks a lot.! I should have been found the setting but I perfectly missed this optin.

**Comment by apache-pine** [comment]
I was having this same issue and this solved it. Thanks!
