### ISSUE TITLE
文档里面怎么连个vscode选项列表都没有写？

### ISSUE THREAD

**Issue by dptr** [shd101wyy/vscode-markdown-preview-enhanced#45]
难道这个插件没有vscode里面的配置项供用户定制吗？

**Comment by shd101wyy** [comment]
在 settings 中搜 markdown-preview-enhanced 就好。

**Comment by shd101wyy** [comment]
https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/usages?id=vs-code
