### ISSUE TITLE
Does the plugin support dark theme when previewing?

### ISSUE THREAD

**Issue by ChenhuaYang** [shd101wyy/vscode-markdown-preview-enhanced#450]
Like Markdown All in One's dark theme.

**Comment by shd101wyy** [comment]
在插件设置里搜索 previewTheme 可以找到预览主题

**Comment by ChenhuaYang** [comment]
感谢！

**Comment by heartacker** [comment]
> 在插件设置里搜索 previewTheme 可以找到预览主题

你好。可以在界面增加一个快速切换 主题的按钮吗？有时候需要截图。就需要浅色的主题。但是我在编辑的时候我更喜欢黑色的主题。
另外就是如果有快速切换的按钮的话，可以方便查看不同主题之间的渲染效果。
