### ISSUE TITLE
how to create an empty table cell if extended table syntax is enabled

### ISSUE THREAD

**Issue by safeizxc** [shd101wyy/vscode-markdown-preview-enhanced#479]
sometimes i need to use the extended markdown table syntax, since i need to merge cells. but if i leave an emtpy cell there, it will be merged automatically, but i just want to create an empty cell by purpose.

then how to have both the extended table syntax and empty table cell working together?

**Comment by Apeiria** [comment]
A workaround is to put &nbsp; in the empty cell. Though I think this is stupid.

**Comment by safeizxc** [comment]
> A workaround is to put `&nbsp;` in the empty cell. Though I think this is stupid.
  
  anyway, it works. thank you.
