### ISSUE TITLE
无法在预览中跳转另一个md文件

### ISSUE THREAD

**Issue by GFDGIT** [shd101wyy/vscode-markdown-preview-enhanced#497]
![image](https://user-images.githubusercontent.com/22742500/119267829-cd0ca500-bc22-11eb-9480-066e98ad42d3.png)
![image](https://user-images.githubusercontent.com/22742500/119267849-e4e42900-bc22-11eb-9a85-0800aa70528c.png)
原本是一个本地md的链接，但在预览中的链接地址却变了，点击后使用浏览器打开，然后提示如图，用vscode自带的预览可以正常跳转。

**Comment by GFDGIT** [comment]
vscode和MPE都是目前最新版本，好像两三个月前的旧版本没有这个问题。

**Comment by ZhengshuaiPENG** [comment]
+1

**Comment by shd101wyy** [comment]
是的我也发现了这个问题。我找个时间修复一下。谢谢！

**Comment by shd101wyy** [comment]
应该是修好了。貌似 vscode 升级后的 api 变化造成的问题。

**Comment by GFDGIT** [comment]
更新后没问题了，感谢 @shd101wyy

**Comment by vangou** [comment]
更新后出现一样的问题，目前vscode版本最新，MPE版本也是最新v0.5.21
