### ISSUE TITLE
doesn't work TOC create when file save

### ISSUE THREAD

**Issue by isuka** [shd101wyy/vscode-markdown-preview-enhanced#499]
environment as follows.

- OS: macOS(Big Sur v11.4)
- VSCode: v1.56.2(Universal)
- Markdown Preview Enhanced: v0.5.18

operation

1. create new markdown file.
2. Markdown Preview Enhanced: Create TOC
3. create some heading
    e.g.
    ```
    <!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=false} -->
    
    # aaa
    
    # bbb
    ```
4. save file

I expect TOC(code_chunk_output) is generated, but not generate it.

best regards.

**Comment by fedlin** [comment]
you'll got itlike this:

```
# aaa
<!-- @import "[TOC]" {cmd="toc" depthFrom=1 depthTo=6 orderedList=false} -->
## bbb
```

**Comment by isuka** [comment]
Thank you response.
but, still not work it.

What are the conditions for a TOC to be generated?

**Comment by shd101wyy** [comment]
@isuka You will have to keep the preview open to get the TOC creation working

**Comment by isuka** [comment]
@shd101wyy 

Thank you. I can also create TOC.
It was because I was writing Markdown without previewing recently.
