### ISSUE TITLE
[question] using a custom font in the preview

### ISSUE THREAD

**Issue by teauxfu** [shd101wyy/vscode-markdown-preview-enhanced#506]
Is there a way to change the font used in the preview?

I'm using the Dendron fork and doesn't seem to have a setting for it, while the regular markdown preview enhanced does

It seems like, however, this extension still exposes some of the regular extension's settings; for example the css theme used in the rendering `markdown-preview-enhanced.previewTheme`

related: #505

**Comment by Will-At-Carrier-Pigeon** [comment]
I was having the same issue yesterday, after much digging around I found the folder where the stylesheets are kept. 

Probably the best idea is overwriting `none.css` as you'll still have access to the other default themes (though you can just build the `.less` files again to restore them).

The path (on linux) is below, on mac i assume its pretty much the same and on windows is probably `user/UserName/.vscode/...`
```
~/.vscode/extensions/shd101wyy.markdown-preview-enhanced-0.5.21/node_modules/@shd101wyy/mume/styles/preview_theme/none.css
```

It would be nice to just have `"markdown-preview-enhanced.fontFamily"` in the settings, but for now at least there's a workaround.

Also note that its not really a good idea to go digging around in node_modules, if the extension updates theres a good chance that the stylesheets will reset too.

**Comment by teauxfu** [comment]
@Will-At-Carrier-Pigeon thanks for the tip! on windows i was indeed able to find the themes css at
`.vscode\extensions\dendron.dendron-markdown-preview-enhanced-0.10.46\node_modules\@dendronhq\mume\styles\preview_theme`
from there it was easy to change the font family

**Comment by Will-At-Carrier-Pigeon** [comment]
@teauxfu Np! Glad to help.

I'd say make a new issue specific to that setting, maybe give some implementation ideas and such. Good luck!
