### ISSUE TITLE
无法在预览中跳转另一个md文件

### ISSUE THREAD

**Issue by violet73** [shd101wyy/vscode-markdown-preview-enhanced#507]
![image](https://user-images.githubusercontent.com/52645705/123433104-acf34b80-d5fd-11eb-9930-311ff446305f.png)

插入了一个本地md的链接，但在预览视图下点击后弹出浏览器打开了一个无法访问的链接，而用vscode自带的预览可以正常跳转。

**Comment by spectereye** [comment]
exact the same error met

**Comment by shd101wyy** [comment]
最新版应该修好了。谢谢
Should be fixed in the latest version. Thanks

**Comment by violet73** [comment]
更新后可正常跳转，感谢 @shd101wyy！

**Comment by shd101wyy** [comment]
我也不知道为啥 vscode 更新后的打开链接总是变。如果以后又变了我还得修 :joy:
