### ISSUE TITLE
无法打开“MPE Preview”: write EPIPE。

### ISSUE THREAD

**Issue by xiaoshi100086** [shd101wyy/vscode-markdown-preview-enhanced#53]
你好，我是markdown的新手，我下载了VS code发现了该插件。其中其他markdown的语法支持都还好，但是只要是写plantuml的语法就会报错。
错误    无法打开“MPE Preview”: write EPIPE。

**Comment by shd101wyy** [comment]
你安装 java 了吗？

**Comment by xiaoshi100086** [comment]
额，我发现是jre的环境变量忘记配置了。我把jre的bin路径添加到系统变量的path中就可以了。:D
