### ISSUE TITLE
Menu Access?

### ISSUE THREAD

**Issue by Raesu** [shd101wyy/vscode-markdown-preview-enhanced#55]
Is there any way to access the features other than the keybinds? Thanks.

**Comment by shd101wyy** [comment]
@Raesu you can right click at the markdown file, then choose `Markdown Preview Enhanced: Open Preview`.   

<img width="1017" alt="screen shot 2017-10-13 at 12 48 44 pm" src="https://user-images.githubusercontent.com/1908863/31559041-daedb90c-b014-11e7-8055-e4636e48eb8c.png">


Or `cmd-shift-p` then enter command.

**Comment by Raesu** [comment]
Good to know, thank you!
