### ISSUE TITLE
Support VS Code for the Web

### ISSUE THREAD

**Issue by kingreatwill** [shd101wyy/vscode-markdown-preview-enhanced#550]
The 'Markdown All in One' extension is not available in Visual Studio Code for the Web.

https://vscode.dev/

**Comment by isidorn** [comment]
:wave: I'm Isidor, a PM from the VS Code team, and we recently announced VS Code for the Web at https://vscode.dev/, which provides a free, zero-install Microsoft Visual Studio Code experience running entirely in your browser.  You can learn more [here](https://code.visualstudio.com/docs/editor/vscode-web). 

We'd like to ensure vscode-markdown-preview-enhanced can run in the web, and we have a guide for enabling extensions for the web [here](https://code.visualstudio.com/api/extension-guides/web-extensions). As a couple of highlights:

- In VS Code for the Web, both the UI and extension host run inside the browser.
- A web extension is structured like a regular extension, but with a different main file: it's defined by the `browser` property
- Access to workspace files needs to go through the VS Code file system API accessible at `vscode.workspace.fs`
- There are currently [three ways](https://code.visualstudio.com/api/extension-guides/web-extensions#test-your-web-extension) to test a web extension

I checked out the extension and I see you have a node dependency on the `path`. Ideally, you should be able to use `vscode fs apis` as a replacement. I am not sure what other node dependencies you might have?

Please let us know if you have questions or feedback on enabling your extension for the web - our team would love to learn from your experiences and collaborate. Thank you!

**Comment by bamurtaugh** [comment]
Hi @shd101wyy! I was wondering if you might have thoughts on this? We're happy to discuss if you have any questions or feedback. Thank you!

**Comment by shd101wyy** [comment]
Hi guys. Sorry for the late reply. The markdown-preview-enhanced package heavily depends on the [mume](https://github.com/shd101wyy/mume) npm package. However, the [mume](https://github.com/shd101wyy/mume)  package uses lots of npm packages and some other dependencies (such as plantuml.jar) that can only run on a local machine. So I would assume in order the migrate markdown-preview-enhanced to the web, we will need to get [mume](https://github.com/shd101wyy/mume)  to run on/for web first. And this process will take a while.  
Thanks!

**Comment by shd101wyy** [comment]
![image](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/assets/1908863/b0b70bcb-97dc-4a9c-bd06-f2286a921ae9)

The MPE for VSCode Web is coming soon :tada:

**Comment by shd101wyy** [comment]
Hi @bamurtaugh . May I ask how to publish both extensions for web and native at the same time?  
Should I just run `vsce publish` and that command will publish both? Thank you!

**Comment by bamurtaugh** [comment]
Great news, thanks for letting us know! Just running `vsce publish` should work - users won't need to see 2 different versions of the extension, they should just be able to install the appropriate version for their current platform. Please let us know if you have any trouble!

**Comment by shd101wyy** [comment]
Thank you for the help @bamurtaugh !

**Comment by shd101wyy** [comment]
MPE now supports VSCode for the Web :tada:
