### ISSUE TITLE
Markdown Preview Enhanced: Toggle  in vscode

### ISSUE THREAD

**Issue by jeffatoptics** [shd101wyy/vscode-markdown-preview-enhanced#578]
In vscode, i am able to use `ctrl+K V` to open preview to the side, but i can not toggle the preview.
- `ctrl+shift+m`  in the MPE documentation does not work, it toggles `the terminal problems screen`
-  i do not find command `Markdown Preview Enhanced: Toggle`  in vscode in commands palette.

Is there any way to toggle preview when i am editing a file

**Comment by zcysxy** [comment]
The command is `Markdown Preview Enhanced: Open Preview to the Side`. The shortcut is `Ctrl+K`, then hit `V` without holding `Ctrl`. Or maybe the shortcut is used by other commands, then you can enter `Ctrl+K Ctrl+S` to change the shortcut. Also, the command is linked to this icon above the document

<img width="399" alt="image" src="https://user-images.githubusercontent.com/48207708/160265906-bf420295-5ec6-4fc2-b9e4-e6e886c23752.png">
