### ISSUE TITLE
can MPE integrate kroki engine directly?

### ISSUE THREAD

**Issue by zhuzhzh** [shd101wyy/vscode-markdown-preview-enhanced#581]
I found kroki support a lots of render engines, which are useful. so I think maybe MPE could use it directly.

**Comment by shd101wyy** [comment]
Kroki will be supported once this PR https://github.com/shd101wyy/mume/pull/296 gets merged.

**Comment by shd101wyy** [comment]
@zhuzhzh Kroki is now supported.

**Comment by zhuzhzh** [comment]
@shd101wyy great, 3ks!
