### ISSUE TITLE
markdown Extended syntax for table not work

### ISSUE THREAD

**Issue by leavesster** [shd101wyy/vscode-markdown-preview-enhanced#59]
Thank you for your plug. 
According to the documt [Extended syntax / table](https://shd101wyy.github.io/markdown-preview-enhanced/#/markdown-basics?id=table) . I can use `^` `>` to combine cell .
But When I use `VSCode 1.17.2 (1.17.2) + Markdown-preview 0.3.0` , it seems not work.
just like this.

<img width="1170" alt="table" src="https://user-images.githubusercontent.com/11785335/32688061-8ef16178-c704-11e7-998e-308d5dd8297c.png">

Here is the plain text

```markdown
|a|b|c|
|---|---|---|
|1|2|3|
|4|5|6|



colspan `>` or `empty cell`:

|a|b|
|---|---|
| > | 3 |
|4||

rowspan `^`

| a | b |
|---|---|
| 1 | 2 |
| ^ | 4 |

```

**Comment by shd101wyy** [comment]
It is disabled by default, you can enable it from the package settings.

**Comment by leavesster** [comment]
Thank you for reply!

It seems other  `Extended syntax` work fine, so I thought It was a bug.
write `"markdown-preview-enhanced.enableExtendedTableSyntax": true` to `setting.json` fixs this.
