### ISSUE TITLE
预览中的本地文本文件链接跳转到浏览器去了，打开失败

### ISSUE THREAD

**Issue by yyangdid** [shd101wyy/vscode-markdown-preview-enhanced#591]
本地文本文件链接跳转到浏览器去了，文件打开失败 。

以前好像修复了这个问题，现在好像又出现了。

vscode版本：1.67.0（22年5月7日最新版）

MPE版本：2022年2月28日版本

**Comment by gtianw** [comment]
我也出现了，之前用得好好的，感觉是vscode更新导致的

**Comment by yyangdid** [comment]
多谢大佬 👍

**Comment by shimushi2172** [comment]
同样遇到这个问题  求答案呀
跳转到类似下面的网页
https://file+.vscode-resource.vscode-cdn.net/c:/ /README.md

**Comment by shd101wyy** [comment]
这个得等我周末才有时间修复了

shimushi2172 ***@***.***>于2022年5月11日 周三21:39写道：

**Comment by shd101wyy** [comment]
应该是在最新的版本 0.6.3 中修复了。谢谢！

**Comment by yyangdid** [comment]
多谢修复 👍
