### ISSUE TITLE
Atom-ish autocomplete

### ISSUE THREAD

**Issue by dtgoitia** [shd101wyy/vscode-markdown-preview-enhanced#60]
Hi @shd101wyy !

I'm a heavy user of your package in Atom, and I want to move completely to VSCode. However, I miss some very useful functionalities such as autocompletion when adding a new line in a bullet list, numbered list or task.

This is the behaviour in atom:
![Atom behaviour gif](https://user-images.githubusercontent.com/21012855/32721794-9f630c76-c85f-11e7-9fa2-d98ccc882423.gif)
Please note that I only pressed enter to add a new line, and the bullet, number or task mark were automatically added.

Does this autocompletion exist in VSCode? If so, how can I enable it?

Many thanks!

**Comment by shd101wyy** [comment]
Hi @dtgoitia 

This plugin only deals with the preview part but not the editing part. You might need to look for some other plugins to achieve that goal. 

Thanks

**Comment by dtgoitia** [comment]
Ah! I see :) Sorry for my request then and thanks @shd101wyy !
