### ISSUE TITLE
front-matter: export_on_save not working

### ISSUE THREAD

**Issue by leavesster** [shd101wyy/vscode-markdown-preview-enhanced#63]
according to [export_on_save ](https://shd101wyy.github.io/markdown-preview-enhanced/#/zh-cn/html?id=%e4%bf%9d%e5%ad%98%e6%97%b6%e8%87%aa%e5%8a%a8%e5%af%bc%e5%87%ba)

Add the front-matter like below: 
```
---
export_on_save:
  html: true
---
```
So the html file will be generated every time you save your markdown file. 

But it seems not work, after I enter `ctrl + s`. The html not change or generate, even I delete the *.html file

**Comment by shd101wyy** [comment]
@leavesster I have take a look when I have time this weekend. Thanks.

**Comment by shd101wyy** [comment]
@leavesster I just tried and it worked fine on my machine. Can I see your markdown file?

**Comment by leavesster** [comment]
@shd101wyy 

just like this 

```
---
export_on_save:
  html: true
---


# here is my test
```

Here is the snapshot 
![default](https://user-images.githubusercontent.com/11785335/33413316-dee089c2-d5cb-11e7-9d98-0e76e4fe6cd4.png)

save as 2.md and then save it by `ctrl + s`. No HTML file has generated

I just reinstall it. The version is 0.3.1

**Comment by shd101wyy** [comment]
Works fine on my Ubuntu machine. What operating system are you using?

**Comment by leavesster** [comment]
MacOS 10.13 and same in Windows. If it work as default. Maybe it is my setting problem ?

Here is my setting:
```
    "editor.fontSize": 16,
    "editor.wordWrap": "on",
    "markdown-preview-enhanced.enableExtendedTableSyntax": true,
    "workbench.startupEditor": "newUntitledFile"
```

I change some code in mume/out/src/markdown-engin.js. But I reinstall `markdown-preview-enhanced`. It should never affect any more.
I will ask my friend to try this.

**Comment by leavesster** [comment]
It seems also not work in my friend's windows 10. which is new for vscode.  He install vscode and restart vscode after install `markdown-preview-enhanced`.

**Comment by leavesster** [comment]
I try this auto save option in my personal computer (macOS 10.13 as well)
At first it not works. But after I reinstall the `markdown-preview-enhanced` and make sure the files deleted. It works everytime I enter `ctrl + s` , maybe I can resolve it myself. seems it just not work in special situation.
I will try other computers tomorrow.

thank for reply~

**Comment by shd101wyy** [comment]
@leavesster I think I know why. You need to have your preview open first to use that feature.

**Comment by leavesster** [comment]
Yeah，You are right！ Thank you

**Comment by leavesster** [comment]
What's more,  also need modify file once after preview open.
