### ISSUE TITLE
vs code 使用 chrom(puppeteer) 导出PDF时总是提示要全局安装puppeteer

### ISSUE THREAD

**Issue by Robothy** [shd101wyy/vscode-markdown-preview-enhanced#65]
在Windows 10 64位 vs code 1.19.1下， 使用使用 chrom(puppeteer) 导出PDF时总是提示要全局安装puppeteer。
**错误** Puppeteer (Headless Chrome) is required to be installed globally. Please run `npm install -g puppeteer` in your terminal. 
而puppeteer已经通过`cnpm install -g puppeteer`命令成功安装过了。

**Comment by shd101wyy** [comment]
是的 windows 下好像有点问题。我有时间了修下。谢谢
