### ISSUE TITLE
Matrices don't display correctly

### ISSUE THREAD

**Issue by panphy** [shd101wyy/vscode-markdown-preview-enhanced#651]
e.g. The following matrices work on the default preview but only show as literally the characters without converting to proper matrices.

$$
\begin{pmatrix}
a &b &c\
d &e &f\
g &h &i\
\end{pmatrix}
\cdot
\begin{vmatrix}
a &b \
c &d \
\end{vmatrix}
=
\begin{bmatrix}
\alpha_{11} &\alpha_{12} &\alpha_{13}\
\alpha_{21} &\alpha_{22} &\alpha_{23}\
\alpha_{31} &\alpha_{32} &\alpha_{33}\
\end{bmatrix}$$

**Comment by ypangelo** [comment]
I figure out a way to display the matrices correctly...

If the `=` sign in my original post is put on a new line between `\end{vmatric}` and `\begin{bmatric}`. VSCode Markdown Preview Enhanced won't be able to show the matrices correctly. However it does work on Jupyter Notebook Markdown cells.

**Comment by heartacker** [comment]
$$
\begin{pmatrix}
a &b &c
d &e &f
g &h &i
\end{pmatrix}
\cdot
\begin{vmatrix}
a &b
c &d
\end{vmatrix}
$$
