### ISSUE TITLE
Is this project alive?

### ISSUE THREAD

**Issue by DoItWithASmile** [shd101wyy/vscode-markdown-preview-enhanced#653]
Looking at the commit history and the issue log, I have to wonder: Is this project even alive anymore?

- commits are only updates to dependencies, but no changed code since late 2020
- closed issues weren't closed by solving it but rather the asking party closed it themselves

I will uninstall the extension for now until this question is answered. No time to waste on a seemingly dead horse

**Comment by DoItWithASmile** [comment]
ended up with a fork and some modifications to move on with my work.

Still would be nice to get a sign of life here.

**Comment by mert-kurttutan** [comment]
> ended up with a fork and some modifications to move on with my work.
> 
> Still would be nice to get a sign of life here.

@DoItWithASmile I am just curious, Are you planning to do something about maintaining this project?

**Comment by DoItWithASmile** [comment]
@mert-kurttutan short answer: no

long answer:

- language is typescript -> I am more the C# guy (came up 30 years ago with Turbo Pascal, Delphi, Borland Pascal, PHP, VB, VB.NET, now C#... switched to product management 10 years ago and only code on the side now to automate processes... not the best coder anymore; damn good software and systems engineer though)
- the main component doesn't seem to be the extension itself, but rather that mume project -> the extension is just a wrapper. the other project is the heart and soul, really
- I am happy to contribute my work though. I am also eager to give credit where credit is due and not claim someone's work as my own. -> I will offer pull requests to this project
- I won't spend the time to go through all the open issues and filter them etc... -> that's what I would do as PO / product manager, which is my day job... but I am not to interested / invested enough in this project to spend a lot of time on it weekly. ;)

---

what I am looking at:
using Markdown as my main storage format since I am converting tons of data into different formats and document types for regulatory and legal purposes. Before writing my own editor - and most likely my own Markdown flavor like 1000+ before me it seems... - I wanted to give VS Code and this extension a shot.

As always: looks good enough and there is "just this one little thing missing" kind of situation. >.<

---

what I am trying to achieve:
publish markdown from a git repository to WordPress (for now). In order to write it though, I would love to have a live preview which applies the same stylesheets and stuff as WordPress and the loaded plugins and themes would. Basically rendering it a lazy person WYSIWYG editor. Sort of....

**Comment by shd101wyy** [comment]
If you want to make contributions to this plugin then please submit PRs to https://github.com/shd101wyy/mume unless it is specifically vscode related.
