### ISSUE TITLE
v0.6.6 is rendering Table of Contents improperly

### ISSUE THREAD

**Issue by djherron** [shd101wyy/vscode-markdown-preview-enhanced#658]
v0.6.6 of Markdown Preview Enhanced became active within my Visual Studio Code editor starting today (2 Jan 2023), and now the Table of Contents automatically generated by the markdown [TOC] does not render properly. See attached image illustrating the problem. 

![mpe-v0 6 6-toc](https://user-images.githubusercontent.com/7301800/210266842-42af2c39-26d2-43bc-91e2-719962f1e474.jpg)

**Comment by nirajbhatt7** [comment]
I see the same issue.

**Comment by Bobarev** [comment]
Same issue.

**Comment by LiweiningMG** [comment]
Same issue., I switched the version back to 0.6.5.

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks

**Comment by djherron** [comment]
Thank you!  v0.6.7 does indeed fix the behaviour I was getting.  And it reveals the new TOC bullet/icon look-and-feel, and its new interactive functionality whereby you can collapse sections/subsections by clicking on their triangle bullet icons.  (For example, notice in my image that I have collapsed Section 2 in the TOC with my mouse.)  Nice one!

![mpe-v0 6 7-toc](https://user-images.githubusercontent.com/7301800/212474130-8489692d-353d-4d3f-acea-eaf7c40c1ac0.jpg)
