### ISSUE TITLE
TOC links don't work on ver.0.6.7

### ISSUE THREAD

**Issue by i3244** [shd101wyy/vscode-markdown-preview-enhanced#668]
Thanks for the great extension!

TOC links like the example below work in the preview window in ver.0.6.6, but not in ver.0.6.7.

```markdown:sample.md
[Link to Features](#1-features)

# 1. Features
```

Anchor links in the HTML converted with the 'HTML (offline)' menu also don't work either.

HTMLs converted with the both versions are below.

- ver.0.6.6

```html:sample.html
<p><a href="#1-features">Link to Features</a></p>
<h1 class="mume-header" id="1-features">1. Features</h1>

```

- ver.0.6.7

```html:sample.html
<p><a href="#1-features">Link to Features</a></p>
<h1 class="mume-header" id="-1-features">1. Features</h1>
```

The '-' at the beginning of the id is added on ver.0.6.7, it looks disturb the action of the link.

Environment:

- Visual Studio Code 1.74.3
- Ubuntu 20.04.5 LTS

Settings:

```json:devcontainer.json
  "settings": {
    "markdown-preview-enhanced.automaticallyShowPreviewOfMarkdownBeingEdited": true,
    "markdown-preview-enhanced.enableExtendedTableSyntax": true,
  }
```

Thank you.

**Comment by pp611** [comment]
When will there be a fix? This tiny bug is very annoying. 

Anyway we can revert back to 0.6.6?

**Comment by shd101wyy** [comment]
Sorry for the reply. Will fix the issue and update the extension this weekend

**Comment by shd101wyy** [comment]
Should be fixed now. Thanks

**Comment by i3244** [comment]
I found that the issue has definitely been fixed.
Thank you!
