### ISSUE TITLE
Mathjax rendering option doesn't take effect.

### ISSUE THREAD

**Issue by kwanswiki** [shd101wyy/vscode-markdown-preview-enhanced#673]
I am trying to switch the math rendering option from katex to mathjax, but I think it doesn't take effect because the it thrown the `PaeseError` message saying about `katex parse error`.

我想将渲染选项中的 katex 更改为 mathjax，但貌似不生效，因为错误信息中显示的依然是 katex 渲染错误。

![微信截图_20230206104134](https://user-images.githubusercontent.com/52689283/216874890-84d0c1fe-f00c-4855-9efa-7cd32bb435ae.png)

I am not sure if i've done it right, maybe there are other settings need to be configure to take effect?

我不清楚是否有其他选项需要配置才可以令这个选项生效？

And I am not sure if it is a duplicate of [#195](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/195) since all other katex equations are rendering just fine.

我不清楚这是否是与 [#195](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/issues/195) 同样的问题，因为其他 katex 公式均可正常渲染。

Is there any advice on how I should further debug this issue?

请问针对该问题有何建议？

plugin version: 0.6.7
vscode version: 1.75.0
os: windows 11

**Comment by shd101wyy** [comment]
这个是关闭预览，再重新打开就可以了
