### ISSUE TITLE
Where to edit MathJax.Hub.Config?

### ISSUE THREAD

**Issue by ketozhang** [shd101wyy/vscode-markdown-preview-enhanced#70]
I've asked this before but I really wish we can edit more than just CSS (at least HTML or even Javascript). I would love to configure `MathJax.Hub.Config` for all previews because I use macros a lot.

Is this supported?

**Comment by shd101wyy** [comment]
https://shd101wyy.github.io/markdown-preview-enhanced/#/math

**Comment by ketozhang** [comment]
I'm sorry I don't understand. I've read the documentations already. Your solution is to use `@import /path/to/js/file` which is okay having to do that for every markdown file is tedious.

Is there absolutely no way to configure how the preview renders. Like having access to the HTML file that the preview uses to render?

**Comment by ketozhang** [comment]
I take that back you're right. The command is `Open MathJax config`. Which is confusing because I typed the keyword "customize MathJax" instead since it follows "customize CSS".

Thank you, please close this.

**Comment by shd101wyy** [comment]
But equationNumber is not well supported in preview. No good solution found yet.

**Comment by ketozhang** [comment]
@shd101wyy  Would love to work with you on that please see #67
