### ISSUE TITLE
Why does markdown-preview-enhanced want to fix my /etc directory?

### ISSUE THREAD

**Issue by enihcam** [shd101wyy/vscode-markdown-preview-enhanced#708]
i got this from vscode notifications:
```
Error: EACCES: permission denied, mkdir '/etc/xdg/mume'
```

could you store whatever you need in `~/.config/mume` instead?

**Comment by shd101wyy** [comment]
It's probably because of this pull request: https://github.com/shd101wyy/mume/pull/234

But you can set the `"markdown-preview-enhanced.configPath"` to specify that directory path.
