### ISSUE TITLE
pass the color theme parameters to style.less.

### ISSUE THREAD

**Issue by byte-clown** [shd101wyy/vscode-markdown-preview-enhanced#716]
I was excited to see the new `previewColorScheme` parameter added to the plugin this morning. This is very practical.

It would be even better if the color theme parameters could be passed to style.less, for example, `@is-dark`.

When switching between the themes github-dark.css and github-light.css, style.less needs to know whether the current theme is light or dark in order to switch the color mode accordingly.

Thank you for your contribution!

**Comment by shd101wyy** [comment]
Hi @byte-clown , we can probably add a class name like `is-dark` to the preview panel. I will do it in the next release :+1:

**Comment by shd101wyy** [comment]
@byte-clown Added 4 classes in the latest release: https://github.com/shd101wyy/vscode-markdown-preview-enhanced/releases

**Comment by byte-clown** [comment]
```less
.mystyle(@is-light) {
    ...
}

.editor-light {
    .mystyle(true)
}

.editor-dark {
    .mystyle(false)
}
``` 

You are really efficient. thx!

Here's a small issue: The attachment of the four classes to the element seems to have a slight delay, which results in a slight delay in the application of custom styles

**Comment by shd101wyy** [comment]
Thank you. I also notice that. Will investigate a solution.
