### ISSUE TITLE
设置 toc为true没有默认打开侧导航

### ISSUE THREAD

**Issue by kakayunmu** [shd101wyy/vscode-markdown-preview-enhanced#75]
`---
html:
  offline: false
  toc: true

toc:
  depth_from: 1
  depth_to: 2
  ordered: true

export_on_save:
  html: true
---`

导出html 后 侧栏还是隐藏的，如何设置能打开页面侧导航就是展开的？

**Comment by kakayunmu** [comment]
生成的html 头部的  front-matter 能隐藏吗？
![](http://onk4ymdmh.bkt.clouddn.com/2222.png)

**Comment by shd101wyy** [comment]
出现这这种情况说明你的 front matter 空格或者是什么不对，正常显示会是 table 或者 code block。front matter
的显示可以在插件设置里设置。

**Comment by kakayunmu** [comment]
![t](http://onk4ymdmh.bkt.clouddn.com/333.png)
在vs code里是正常的 但是导出html 就不行了

**Comment by shd101wyy** [comment]
把你的文件发我看看？

**Comment by kakayunmu** [comment]
[RZG_QYWXAPP_Api.zip](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/1658218/RZG_QYWXAPP_Api.zip)
文件在此

**Comment by kakayunmu** [comment]
我的系统环境是 win10  和这个有关系吗？

**Comment by shd101wyy** [comment]
@kakayunmu 我试了下，好像是 encoding 的问题。你的文件的 encoding 格式是 `UTF 8 with BOM`。改成 `UTF 8` 就好了。附件是我改过格式的。

[RZG_QYWXAPP_Api.zip](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/files/1671631/RZG_QYWXAPP_Api.zip)

**Comment by kakayunmu** [comment]
好的  谢谢您

**Comment by kakayunmu** [comment]
好的  谢谢您
