### ISSUE TITLE
After preview 'tab' button

### ISSUE THREAD

**Issue by uguruysal0** [shd101wyy/vscode-markdown-preview-enhanced#78]
After previewing a markdown,  'tab' button does not work as I expected. In edtior I can not even tab.

**Comment by RoyiAvital** [comment]
How do you even open Preview? On VS Code 1.19.2 the Preview doesn't show any feature of this extension.

**Comment by uguruysal0** [comment]
Well this is not related to preview I clsoe this issue, after updating it is fixed.
