### ISSUE TITLE
feature request: support quarto markdown files *.qmd

### ISSUE THREAD

**Issue by rtockner1** [shd101wyy/vscode-markdown-preview-enhanced#860]
It would be very nice if markdown preview enhanced would be working with quarto  (https://quarto.org/) markdown files (*.qmd) and not only with RMarkdown files. 
In particular, 
 - the  preview a *.qmd file (and not ony a *.rmd),
 - rendering a file via quarto (beside pandoc) 
 -  and the support of the quarto "callout" blocks 
 
would really be a wonderful new feature. 

Thanks 

Reinhard

**Comment by ChoCho66** [comment]
I also have the same need.
When I edit qmd files or rmd files, it is very convenient to use this extension to preview.
I wonder if this extension can support previewing qmd and rmd files first?
For example,
`document.languageId === 'markdown'` changed to `(document.languageId === 'markdown' || document.languageId === 'quarto')` in [here](https://github.com/shd101wyy/vscode-markdown-preview-enhanced/blob/750ecaba0a99fed520109bacbbdf519c34e34827/src/utils.ts#L68C5-L68C39).

**Comment by shd101wyy** [comment]
Oops sorry I missed this issue. Added to my TODO list :+1:

**Comment by shd101wyy** [comment]
Done. I also added a new setting `markdown-preview-enhanced.markdownFileExtensions` which includes `.qmd`.
