### ISSUE TITLE
能否采用 prismjs 进行语法高亮?

### ISSUE THREAD

**Issue by liushilive** [shd101wyy/vscode-markdown-preview-enhanced#92]
期望能采用 prismjs 进行语法高亮。

**Comment by shd101wyy** [comment]
zhe ge wo xian guan le, ben shen yong de jiu shi prism.js
hui zai xia yi ge ban ben yong zui xin de prism.js

I will close this issue now, because it is using prism.js.  
I will use the newest version of prism.js in next release.

xie xie
