### ISSUE TITLE
是否可以更新mathjax 3.1？

### ISSUE THREAD

**Issue by yfzhao20** [shd101wyy/vscode-markdown-preview-enhanced#936]
看起来这里的mathjax 是2.7.5 ，是否可以更新最新的mathjax3.1，以获得更多的功能？

![image](https://user-images.githubusercontent.com/80528249/122386117-20fb7700-cfa0-11eb-92b1-0378c63eee69.png)

另外很多mathjax可以实现的功能，比如化学包`\ce{}`，尽管源文件里有`mhchem.js`，但是仍然不能使用它。

markdown preview enhanced已经更新到`0.5.21`
使用vscode。

**Comment by shd101wyy** [comment]
现在支持 MathJax V3 了。
