### ISSUE TITLE
[Request/Need Help] Update MathJax inclusion to MathJax 3 for font variety

### ISSUE THREAD

**Issue by AndreLouisIssa** [shd101wyy/vscode-markdown-preview-enhanced#956]
I want to use the font "NeoEuler" for the inline math, but I can't get MathJax 2 to use it by changing the fonts myself in the local extension cache and in the MathJax config for the extension.

So I tried to use the style.less to !important override the style of the span elements to font-family: "NeoEulerMedium"
This works for the preview display and the HTML export (both offline and cdn hosted (btw the cdn link is deprecated)), but when I save that HTML export to PDF or when I export to PDF through Chrome (Puppeteer) it uses the MathJax font instead.

So I tried to create a userscript that deletes the style attribute of every "mi" and "mo" class object so the style could get inherited from the overall page. Again this works for the HTML export but not for either way of getting a PDF out (including exporting it from chrome while the userscript is working).

Then I tried to export it to HTML then edit it myself before the PDF export, this just revealed that the HTML source doesn't bake the resulting elements so this doesn't have any way of helping me.
Even baking the HTML post-js rendering (via https://stackoverflow.com/questions/10144820/get-the-html-of-the-javascript-rendered-page-after-interacting-with-it and saving it to a new HTML and then exporting that to PDF) doesn't solve it.

I'm considering rewriting the whole document in LaTeX itself as I have managed to solve this problem for my LaTeX embeds using the eulervm package. However I want to use 4 different fonts and so far I have only succeeded to embed LaTeX with 2 fonts (one math and one text, not 3 text and 1 math). 
And the whole point of this exercise was to avoid writing the whole thing in LaTeX so the source is easy to read and layout.

My only other option is to overwrite the MathJax version this extension uses to be MathJax 3 but as I understand it, MathJax 3 has a slightly different deployment and interface, so I am not sure how to do this. 
Changing the src link in the cnd hosted HTML export to "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" doesn't fix the problem, and on top of that half the elements go missing.

Another option could be to take a screenshot of the rendered page and embed that in a pdf (because the image exports have bugged spacing I can't use those directly). But this just feels very wrong.

(Also switching it to KaTeX it doesn't even finish rendering and previously when it did finish rendering it just produced empty elements)

**Comment by shd101wyy** [comment]
MathJax V3 is just supported now.
