### ISSUE TITLE
Support for Diagrams via Kroki

### ISSUE THREAD

**Issue by dannief** [shd101wyy/vscode-markdown-preview-enhanced#965]
I recently started using [Kroki](https://kroki.io/). It supports many diagram libraries. It would be great to be able to visualize, in markdown, all the diagram types that Kroki supports

**Comment by shd101wyy** [comment]
Kroki will be supported once this PR https://github.com/shd101wyy/mume/pull/296 gets merged.

**Comment by jankap** [comment]
This is awesome! What's going on, so many nice updates, love it! Thank you!
