### ISSUE TITLE
[Feature Request] Highlighting in Preview

### ISSUE THREAD

**Issue by rmrnc** [shd101wyy/vscode-markdown-preview-enhanced#97]
With MPE supporting CriticMarkup's highlighting feature it would be nice to highlight text in preview mode and have the source file modified accordingly.

**Comment by kachkaev** [comment]
That's an interesting suggestion @rmrnc!

AFAIK, CriticMarkup supports [multiple marks](https://github.com/CriticMarkup/CriticMarkup-toolkit/#the-basic-syntax). How would you let users pick the appropriate mark, UI-wise?

**Comment by kachkaev** [comment]
Right. The UI could roughly look like this if the feature gets implemented:

<img width="842" alt="screen shot 2018-04-04 at 18 45 04" src="https://user-images.githubusercontent.com/608862/38324481-62ab911a-3838-11e8-853c-144af16acd83.png">

_I did this sketch by appending the following lines to [`mume → webview.ts#L456`](https://github.com/shd101wyy/mume/blob/286e8f16936be02acf1dfbdb256b01e08a41aad5/src/webview.ts#L456)_

```js
          sep4: "---------",
          critic_markup: {
            name: "CriticMarkup",
            items: {
              critic_markup_none: {
                name: "no action on select",
                type: "radio",
                radio: "critic_markup",
                value: "none",
                selected: true,
              },
              highlight: {
                name: "highlight",
                type: "radio",
                radio: "critic_markup",
                value: "highlight",
              },
            },
          },
```

To be honest, I see quite a lot of work behind the actual implementation and I'm not sure I'd be able to lift this. However, if you're fancy submitting a PR, I'm happy to take a look and help you with finishing it.

**Comment by rmrnc** [comment]
Thank you for taking the request into consideration. Unfortunately, the JS arrow is missing in my quiver of programming languages. I apologize for not contributing any code.

**Comment by kachkaev** [comment]
No worries! Happy to return to this later if anyone wants to volunteer with a PR.

**Comment by mattorp** [comment]
My company needs this feature and could look into implementing it. But if anyone is up for the task we'll happily pay a bounty fee. In that case, should it go GitHub sponsors or can we send it directly to the contributors of this issue?

**Comment by mattorp** [comment]
@kachkaev is there an existing implementation for getting the highlighted text? I'm trying to implement this feature now

**Comment by serranomorante** [comment]
For those using `pandoc parser`, you can follow [this guide](https://shd101wyy.github.io/markdown-preview-enhanced/#/extend-parser) to make highlights work on the preview.

Use the following snipped:

```javascript
module.exports = {
  onWillParseMarkdown: function (markdown) {
    return new Promise((resolve, reject) => {
      markdown = markdown.replace(/==([^=\n]+)?==/gm, "<mark>$1</mark>");
      return resolve(markdown);
    });
  },
  ...
```
